### ISSUE TITLE
[Request] puff time in H:M:S

### ISSUE THREAD

**Issue by Starbuck3733T** [maelstrom2001/ArcticFox#1]
I really liked that myevic had the puff time in H:M:S - can a format option be added for puff time on the main screen?

**Comment by maelstrom2001** [comment]
Thanks for suggestion, maybe it will be added later.

**Comment by Starbuck3733T** [comment]
thanks, great work so far. nice to see you on github! I have been following using google translate so far and you are amazing.

**Comment by vendeghlajos** [comment]
Would be nice!

**Comment by TBXin** [comment]
Done in the [ArcticFox 170103](https://github.com/maelstrom2001/ArcticFox/releases/tag/170103).

You can switch between two styles: seconds (without zeros) and H:MM:SS.
To change style you should use [NFE Toolbox](https://github.com/TBXin/NFirmwareEditor/releases/tag/6.4).
