### ISSUE TITLE
USB Charging Control ?

### ISSUE THREAD

**Issue by vapinggirl** [maelstrom2001/ArcticFox#105]
Hey there :)

Is it possible to Control usb charging current via Software ? A configurable limitation would be really great to be able to smoooooothly Charge overnight and save battery live and charging circuits

**Comment by TBXin** [comment]
Hello,

Firmware is controlling charging process for all multi-cell devices (except devices with parallel battery connection).

Most of devices have 0.5A charge limit and only new devices like RX300 and Pico Dual have 1.5A limit.

**Comment by Sanaki** [comment]
> Most of devices have 0.5A charge limit and only new devices like RX300 and Pico Dual have 1.5A limit.

**Comment by spattinson** [comment]
I think OP wants configurable slower than normal charging? Most in device chargers are something like 0.5C anyway which is well within recommended limits for lithium batteries anyway. Probably no benefit in this option?

**Comment by TBXin** [comment]
> Probably no benefit in this option?

Absolutely.
