### ISSUE TITLE
Support for iStick Power/iPower new 1.03 firmware and 100 watt mod

### ISSUE THREAD

**Issue by iJo09** [maelstrom2001/ArcticFox#107]
I see there's no support for the new iPower 1.03 firmware.. can you please add it and make the battery do 100 watt (like with VTCFont's patch)?

**Comment by TBXin** [comment]
??? 
This is a custom firmware repository. And our firmware is supporting iPower devices.

**Comment by iJo09** [comment]
Ok so can you change the maximum power output to 100w on iPower? As I said there's a patch for the original fw and it doesn't do nothing bad

**Comment by TBXin** [comment]
Single battery can't give you 100wats, so, patch is useless.

**Comment by iJo09** [comment]
So not even 80.. plus it's an integrated battery and certainly isn't at the level of a high-end vape battery

**Comment by maelstrom2001** [comment]
Maximum power limit for all devices is set to value from recent original firmwares. When Eleaf will increase it to 100 W for iPower - no problem.
