### ISSUE TITLE
Add a option 'reset counters?' screen calling to a **Clicks** menu.

### ISSUE THREAD

**Issue by CCCheshire** [maelstrom2001/ArcticFox#110]
I think it would be good to add possibility to assign a call 'reset counters?' screen in a **Clicks** menu.
(Same screen as on battery change).
Some people need to count puffs for one tank filling or even reset puffs after each vaping session. (Holy Molly, I made 50 puffs already! I must make a pause! :))
Or any other quick procedure of counters quick reset would be nice.

**Comment by maelstrom2001** [comment]
Added in latest nightly.
