### ISSUE TITLE
I have a ! next to the battery icon.

### ISSUE THREAD

**Issue by velkeibalesz** [maelstrom2001/ArcticFox#113]
Hi! I have updated the Arcticfox fw from the earlier release to 170201 on my vtwo mini and vtc mini.  On the vtwo mini everything alright, but the the vtc mini show a ! next to battery bar.
Before updating I have do a backup for the profiles from the vtwo mini. After that I installed the update to the mods. The installing ok, i upload the toolbox backup to both devices. Working ok, but the vtc mini show a !. I changed the battery to another one, bit the ! still showed. Whats the matter? Sorry for my english.

**Comment by TBXin** [comment]
From readme:
> LSL - Light Sleep Mode, for devices without secondary oscillator keep RTC accurate. It takes some more energy in standby mode, so user will be warned by ! sign right of battery indicator;

**Comment by velkeibalesz** [comment]
Thank you.. :)
