### ISSUE TITLE
Vtc basic support

### ISSUE THREAD

**Issue by Wietjuh** [maelstrom2001/ArcticFox#116]
A friend of mine has the VTC Basic and i think there is a different internal battery.

Has anybody tried it yet for this device? Can someone confirm compatability?

Thanks in advance

Wietjuh

**Comment by TBXin** [comment]
This is not enough?

![](http://i.imgur.com/NTBxBw2.png)

**Comment by maelstrom2001** [comment]
Battery discharge profile should be set to GEN, Basic has the same battery type as in Cuboid Mini, eGrip, VTwo etc. Different capacity, but the type and discharge curve are identical.

**Comment by Wietjuh** [comment]
Tnx Maelstrom, 

And to TBXin, last time i tried with a december build the device was decharging faster than with regular software and the voltage wasn't correct. It read in the live monitor just 3.7v even fully charged. So i will try later tonight for the newest build..

**Comment by TBXin** [comment]
@Wietjuh perhaps it was a bug that we are fixed later.
At this point eVic Basic shoulde use correct discharge profile in our firmware.

**Comment by Wietjuh** [comment]
It reads the correct voltage now and it works like a charm! Thanks!
