### ISSUE TITLE
[Question] Cuboid Owners, the 25a output limit is still there ?

### ISSUE THREAD

**Issue by ceinro** [maelstrom2001/ArcticFox#123]
As you know the Cuboid has 25A limit on the output. So you can only fire >0.3 builds with full 200w. 

Upgrading to this firmware will change or keep that limit ? 

Thanks.

**Comment by maelstrom2001** [comment]
Limit will be [kept](https://github.com/maelstrom2001/ArcticFox/issues/82#issuecomment-275242367).

**Comment by ceinro** [comment]
Thank you for the answer !
