### ISSUE TITLE
evic AIO

### ISSUE THREAD

**Issue by Daveee10** [maelstrom2001/ArcticFox#124]
Sometimes when changing battery, the device increase power and the buttons doesn't works. The only thing what solve the issue, how I'm connecting the charger. After connect the charger the device works good, but sometimes after deep sleep, the issue goes back.. I found this bug with nightlies and the latest stable. With OFW this issue can't reproduceable.

Sorry for my bad english

**Comment by maelstrom2001** [comment]
Have you the same issue on previous stable release? It will be very helpful if you can say when exactly it happened (in which build problem appears).
