### ISSUE TITLE
Lock Control?

### ISSUE THREAD

**Issue by StodgyWaif** [maelstrom2001/ArcticFox#128]
Is it possible to set one of the click controls to lock?

**Comment by TBXin** [comment]
Lock what? Lock resistance? Lock device? Lock +/- buttons? Lock something else?

**Comment by StodgyWaif** [comment]
Yes lock the +/- buttons.

**Comment by TBXin** [comment]
@StodgyWaif 

Hm, at this moment - no, but you can lock clicks pressing and holding +/- simultaneously.
