### ISSUE TITLE
Temperature in 1°C steps?

### ISSUE THREAD

**Issue by dabugen** [maelstrom2001/ArcticFox#129]
Hi,

first off: thanks for the great MyEvic fork that you´ve created, nice work! I was wondering how I can set the temperature in 1°C steps, it always jumps in 5°C steps and I can´t seem to find an option to set it to 1°C steps like in the MyEvic firmware. Can you help?

Thank you so much:)

**Comment by TBXin** [comment]
Hi,

1. Why are you think that ArcticFox is a myEvic fork?
2. Temperature regulation by 1 degree is completely useless, because device can't give you such accuracy while calculating temperature from resistance (caused by low accuracy of the internal ohm shunt).

**Comment by dabugen** [comment]
Hi,

1. The code looks similar at places, that´s why.
2. Regardless what you think, it is not useless, I have happily used the 1°C increments on the MyEvic firmware, it was one of the reasons I have loved it so much and it makes a big difference to me, even if the regulation is not spot on, I still feel the difference between for example 220°C and 223°C (compared to 225°C). I could argue the same about the 1 Watts steps too (that they are useless and not noticeable and 5W steps are fine). But no worries, going back to MyEvic now, just wanted to give Arctic Fox a try, but without the 1°C steps, it´s nothing for me. And you, with your aggressive tone, are not the kind of guy I would like to support at all.

Good bye.

**Comment by TBXin** [comment]
Good bye.

**Comment by dabugen** [comment]
Russians.... So true what they say about you.

**Comment by TBXin** [comment]
Nice try, dude.
You can express your aggression elsewhere.

If you don't like my answers it's only your problem, not mine.
I tried to explain that there is no reason to make such adjustments, but you decided to prove to me that your subjective opinion is more important than the real thing.

**Comment by dabugen** [comment]
It makes a difference, MyEvic firmware is the proof, if you believe it or not, I give a shit, it makes a difference for me, got that? Back to MyEvic, stick your stinking fox up your ass, OK?
