### ISSUE TITLE
Back to original FW

### ISSUE THREAD

**Issue by MEPhoenyx** [maelstrom2001/ArcticFox#131]
Hi, into my Facebook group ask someone. It's possible go back to original Firmware?

Thanks for answering.

**Comment by maelstrom2001** [comment]
Yes, any time.

**Comment by TBXin** [comment]
@MEPhoenyx 

Hello,

Yes, you and any one else can install original firmware at any time. Just choose original firmware file in the NToolbox Firmware Updater or Original Updater Utility for devices.
