### ISSUE TITLE
Clock gains

### ISSUE THREAD

**Issue by mntn-dev** [maelstrom2001/ArcticFox#132]
after 24h, clock is around 30min fast; changed batts 2 or 3 times within.
[RX 2/3, AF 170201]

**Comment by maelstrom2001** [comment]
You have [to calibrate](https://github.com/maelstrom2001/ArcticFox/issues/66#issuecomment-273534875) Clock Speed or use software emulation:
`X32 = Off`
`LSL = On`

**Comment by mntn-dev** [comment]
thanks!
