### ISSUE TITLE
Shut down animation 

### ISSUE THREAD

**Issue by override187** [maelstrom2001/ArcticFox#137]
Hi, just to say that this firmware of yours is simply amazing. Have one suggestion to add some shut down animation, because when turning off device when screen is off you don't know if device is powered off so must check it. 

Thx

**Comment by maelstrom2001** [comment]
Hello! See #122, done in nightly.

**Comment by override187** [comment]
Nice, thank you and keep up good work.

**Comment by maelstrom2001** [comment]
Thank you! :)
