### ISSUE TITLE
Setting Clock 

### ISSUE THREAD

**Issue by anfichtn** [maelstrom2001/ArcticFox#14]
Specially Devices without backup battery...  Is there a way to update the date and time informations with any android app by only connecting usb to the phone?

**Comment by maelstrom2001** [comment]
No. Date/time autosync is available with PC running NFE Toolbox only.

**Comment by MoDuLah** [comment]
Simply put the device on a usb power supply while changing battery/ies ;)

**Comment by maelstrom2001** [comment]
"Great" advice for mods with 2 or more batteries.

**Comment by MoDuLah** [comment]
With disabled charging it just provides enough power to don't lose the time settings. ^_^

**Comment by TBXin** [comment]
You can damage your device this way, also, if the atomizer is plugged this will lead to the constant on / off board.

**Comment by maelstrom2001** [comment]
If somebody forgot to disable this option, he will have to buy new Cuboid. So, please...

**Comment by JohnW383** [comment]
I found out tha with my rx200, if I change the back 2 batteries 1 at a time, take out the left leaving the right one in, put new one in left then change the right, the clock saves the time. I'm just trying to get the clock speed right, it keeps running fast, but I'm playing with the speed and it's getting closer.
