### ISSUE TITLE
Wismec Reuleaux 2/3 wrong profile after battery change

### ISSUE THREAD

**Issue by Vapefreak** [maelstrom2001/ArcticFox#141]
When I charge my batteries and replace them in my mod the automatism for detecting the right profile seems to not work.
Is that issue a known issue? Can someone reproduce it?
I tried to decrease the range in smart settings to 4%, still got that first power on problem.

**Comment by TBXin** [comment]
Hello,

This is happened because your profile 1 have same resistance as your primary. Firmware is looking for first profile with suitable resistance- range for your atomizer.

**Comment by Vapefreak** [comment]
Ok, that can be indeed. Thanks for the fast answer!
