### ISSUE TITLE
custom edit

### ISSUE THREAD

**Issue by obarone** [maelstrom2001/ArcticFox#142]
How can i edit the arctic fox sofware?
Thanks

**Comment by TBXin** [comment]
Hello,

For what reason you want to edit ArcticFox firmware?

**Comment by obarone** [comment]
I'm a student of IT and I want just to see if I can improve something inside the firmware and maybe commit it to the official one

**Comment by TBXin** [comment]
I see. At this moment source code is not available for public.
We are not planning to make it public it at this point.
Anyway, you can submit your suggestions in form of issues and we can talk about them.

Best regards!

**Comment by obarone** [comment]
My improvement are:
-Logo mode: fix logo on the screen, and return to the classic info screen only when press on +/- buttons
-Diaable clock(for energy) and disable the visible clock(like screensaver)
And, maybe a custom icon on the battery info(that's only because I use the percentage info, and the icon of the battery is useless)

**Comment by TBXin** [comment]
> Diaable clock(for energy) 

Clock does not consume any extra energy until you are not turn on LSL mode.

> and disable the visible clock(like screensaver)

Just turn off screensaver and clock and you will never see them.

> And, maybe a custom icon on the battery info(that's only because I use the percentage info, and the icon of the battery is useless)

You can edit battery icon in the NFirmwareEditor.
