### ISSUE TITLE
[ENHANCEMENT?] Shutdown bootanimation

### ISSUE THREAD

**Issue by Dil3mm4** [maelstrom2001/ArcticFox#146]
Hello, 
I don't want to flood the issue section of this awesome custom firmware, but I'm pushing everything that comes in my mind, if source were available I could push it directly or fork, but I understand your choice.
If possible, a shutdown bootanimation would be nice. 
Thank you for your time.

**Comment by maelstrom2001** [comment]
#122

**Comment by Dil3mm4** [comment]
Link to the nightlies?

**Comment by maelstrom2001** [comment]
https://github.com/maelstrom2001/ArcticFox/wiki/Changelog
