### ISSUE TITLE
Strange battery behaviour

### ISSUE THREAD

**Issue by Dil3mm4** [maelstrom2001/ArcticFox#147]
Hello, 
battery seems to discharge faster.
After 5 puffs flows from 80% to 75%. 
Any chance that battery stats affect this ? 

edit: disconnected by 10 min from power surge, puffed 6/7 times - 100% -> 95%

**Comment by TBXin** [comment]
> Any chance that battery stats affect this ?

Sure.

**Comment by Dil3mm4** [comment]
@TBXin what's the suggested thing to do? (btw other 7 puffs 91%)

**Comment by TBXin** [comment]
@Dil3mm4 
1. how old is yout battery?
2. What battery profile you are chosen in the settings?
3. you can measure voltage on the battery with a more precisely tool, like a voltmeter and see what is going on.

**Comment by Dil3mm4** [comment]
1: 3 days old
2: VT5 profile (as per battery spec)
3: I don't have knowledge to read such a specific sheet

Il 18/feb/2017 13:58, "ReikoKitsune" <notifications@github.com> ha scritto:

**Comment by TBXin** [comment]
@Dil3mm4 i see, your problems will go away if you set your battery profile in the device menu to the "GEN".

**Comment by Dil3mm4** [comment]
@TBXin All done. 
I will try a full discharge and then I will charge it back and see if works as expected.
I'll update the issue when I got some results.
Thank you for your interest.

**Comment by Dil3mm4** [comment]
Works good, but I can't get why it doesn't with VT5 battery profile.

**Comment by TBXin** [comment]
@Dil3mm4 because VTC5 profile is not so good in the our reality ^^
