### ISSUE TITLE
Can arctic fox support flappybird like myevic clock select

### ISSUE THREAD

**Issue by ozomax1997** [maelstrom2001/ArcticFox#148]
If the arcticfox firmware supported flappybirds it would be absolutely perfect!

**Comment by TBXin** [comment]
Hello,

Flappy Bird was removed along time ago, to get more space in the ROM for more useful things.

**Comment by Hunterror77** [comment]
I agree there are much better devices to play games than your e-cig... :P

**Comment by docdeath** [comment]
mmm flappybirds forgive me if wrong but its e cig not some kids toy

**Comment by MoDuLah** [comment]
Maybe Tetris would be a better game-choice (and Tetris is not for kids :P)
