### ISSUE TITLE
What I'd like to see added

### ISSUE THREAD

**Issue by wulfgrim** [maelstrom2001/ArcticFox#150]
First off, awesome firmware, thank you so much for this. And taking the time to continue to update/support this, I'm very excited to see what It could become.

Firstly, I'd like to see a click lock function added in the "controls tab" in the click drop down. - locks all input/fire buttons from  accidental press

I too would like a AM/PM clock, but I'd also like the function to disable the clock for devices like rx200, etc that don't have internal oscillators, there's not much of a point as every time I change the batteries the clock resets to 00:00 01/01/1980 something. on my evic vtwo the clock works flawlessly.

I think it would also be nice to be able to add new TFR materials and edit their names , I can't seem to figure out how to do this, and to have the ability to import from a csv file - *** I would really love a way to stop "temp protected" from flashing and just show the temperature. I don't care/want to know that the TC mode is doing what it's supposed to.

TC mode on my evic vtwo mini works pretty darn well on stainless, it doesn't work nearly as well on my rx2/3.

**Comment by wulfgrim** [comment]
Oh, and I noticed the puff counter, and puff time maxes out at 99,999 puffs and 99,999 seconds (which is a mear 27 hours of puffing) so if there was a box to disable recording puffs to save memory usage that might be useful too.

out of curiosity, how many kb of rom do they put on these SOC's?

**Comment by docdeath** [comment]
as for rx,s clocks  you can disable in the tool box and i use the clock and never been a problem to my self and why am and pm ? 24 hr is fine

**Comment by forkoz** [comment]
In the US AM/PM is used more than 24hr time. The date being reversed is actually distracting though. For battery changes it should write the last date/time to memory and go from that instead of resetting to the beginning. Even if it was a little off its better than reset.

**Comment by wulfgrim** [comment]
^ this, the date being backwards can be a little confusing. and While I don't mind the 24 hour clock. having an option for a 12 hr or am/pm would be nice. not sure it would be terribly difficult to implement.


doc, for some reason it didn't write it to memory, and I'm more so glad, I wouldn't want the clock wearing out the writes of the NAND flash inside the chip anyways. I just disabled it. no biggie.

**Comment by wulfgrim** [comment]
Is it possible to show the clock on charging screen?

**Comment by maelstrom2001** [comment]
@wulfgrim enable "Clock on main screen" option, and clock will be on charging screen too.

**Comment by Sanaki** [comment]
> what I would really like to see is the ability to upload TFR/TCR csv files and create my own custom materials. that's something evolv has that this software suit lacks at the moment.

@wulfgrim ArcticFox supports this properly. I didn't see it at first either, but take a look at #51.
