### ISSUE TITLE
VT6 battery profile......

### ISSUE THREAD

**Issue by IngoPOW** [maelstrom2001/ArcticFox#151]
hi,

what profile should be used in the battery section for vt6 cells?
what about adding it into one of the next releases?
think they are sold more and more atm.

regards,
ingo

**Comment by Vapefreak** [comment]
Oh yes I'm using VTC6 batteries as well. It would be enough to get the values for the curve of these batteries.

**Comment by IngoPOW** [comment]
do you want the 2A, 3A or 5A discharging diagram?

**Comment by Vapefreak** [comment]
The curves are on the Internet, but which one should be used? And what are the right values? 
Which one is used for the vtc5?

**Comment by TBXin** [comment]
> what profile should be used in the battery section for vt6 cells?

GEN. He is applicable to all kind of batteries.
