### ISSUE TITLE
2nd battery on eleaf TC100

### ISSUE THREAD

**Issue by matarum** [maelstrom2001/ArcticFox#155]
I put AF170201 in my eleaf TC100 but it is not finding two batteries. only one.

p.s. could it be translated in italian? how? could I help?

**Comment by TBXin** [comment]
Hello,

iStick TC100W uses parallel battery connection, so, technically for software is a single battery ^^

> p.s. could it be translated in italian?
What exactly? NToolbox already have Italian translation.

**Comment by matarum** [comment]
ok, parallel connection, got it.

and, ok, i missed language packs in NToolBox.

Thanks
