### ISSUE TITLE
PICO DUAL wont power on

### ISSUE THREAD

**Issue by ZeusBomb1997** [maelstrom2001/ArcticFox#156]
I have bought my eleaf Pico dual 200w kit with melo 3 mini i have user my box 1 day but today my box dont work. The box cant be powered in the display is Black (the box dont work this is not the stealth mode) i have try another battery 18650 but is the same and the battery is charge.. help me please

**Comment by maelstrom2001** [comment]
Try to flash stock firmware. Links are at the bottom of [product page](http://www.eleafworld.com/pico-dual/).

**Comment by ZeusBomb1997** [comment]
I'm already in stock firmware 
And the eleaf updater Can recognize my Pico dual but my Pico dont Power on

**Comment by maelstrom2001** [comment]
Well, if it don't work on stock firmware, return it to seller, it seems to be a hardware failure.

**Comment by ZeusBomb1997** [comment]
And if i have upgraded your firmware i have the garantee?

**Comment by TBXin** [comment]
@ZeusBomb1997 you should read warranty card that should be provided with the box, i think this kind of information can be there.

**Comment by ZeusBomb1997** [comment]
The firmware is not menzioned in the warranty 
And Sorry for my bad english

**Comment by TBXin** [comment]
@ZeusBomb1997 no problem and good luck with your devices!

**Comment by ZeusBomb1997** [comment]
Thank you @tbxin  @maelstrom2001
