### ISSUE TITLE
Add feature: export/import Power curves

### ISSUE THREAD

**Issue by smok-e** [maelstrom2001/ArcticFox#157]
Would it be possible to add the import and export of power curves? 
Like in the material and battery tabs?
Imho it would be an nice addition.

**Comment by smok-e** [comment]
what does the invalid label mean?

**Comment by TBXin** [comment]
Mean that this kind of issues are not appropriate for this repository.

**Comment by Starbuck3733T** [comment]
open the issue with the Ntoolbox repo, not the firmware. this isn't a firmware issue, it's an app feature request

**Comment by smok-e** [comment]
ok, I will put it in the Ntoolbox repository.
