### ISSUE TITLE
Showing "C" instead of "W" for power

### ISSUE THREAD

**Issue by andreivoinea93** [maelstrom2001/ArcticFox#158]
http://imgur.com/a/g0AiQ

It should show 220*C, 100W. The same thing happens on classic screen as well.

Running last nightly on Evic Primo.

**Comment by maelstrom2001** [comment]
C instead of W right of power value indicates that you're using power curve.

**Comment by andreivoinea93** [comment]
Oh, great! Didn't know that.

**Comment by maelstrom2001** [comment]
Also, there can be P instead of W when you enable preheat option. Will add this info to readme :)
