### ISSUE TITLE
best way to clean install

### ISSUE THREAD

**Issue by docdeath** [maelstrom2001/ArcticFox#159]
is there a best way to clean install firmware

**Comment by maelstrom2001** [comment]
Before updating firmware create backup of your settings with NToolbox. Then update firmware and perform dataflash reset:
![](http://i.imgur.com/nuPZOjJ.png)

Unplug box from USB, remove and re-install battery(-ies). Now your box is in default state, and you can connect it to NToolbox and restore settings from backup.

**Comment by docdeath** [comment]
@maelstrom2001  thanks
