### ISSUE TITLE
new nightly

### ISSUE THREAD

**Issue by bashroot42** [maelstrom2001/ArcticFox#160]
hi , i have downloaded the last 2 nightly, but when try to upload to my istick pico ill give me an error ,is not for my device?

Opened firmware file is not suitable for the connected device,

Thanks for your good work!

**Comment by maelstrom2001** [comment]
Please [update NToolbox](https://ci.appveyor.com/project/TBXin/NFirmwareEditor/branch/master/artifacts). All recent nightlies requires recent PC software.

**Comment by bashroot42** [comment]
Done! many thanks.
