### ISSUE TITLE
Current leakage/Battery Drain on Standby @ iStick TC100W

### ISSUE THREAD

**Issue by Tiankay64** [maelstrom2001/ArcticFox#165]
Hello

Im running NFE Toolbox 1.5 and ArcticFox Build 170201 on both my iStick TC100W and my Wismec RX200S. It runs jus fine on the 200S without any Problems, but i noticed something potentially dangerous on my TC100W. If i leave the Mod alone for some time, something is draining the batteries. This wasnt hapenning with the original 120W Firmware so im sure its a software problem. But the drain doesnt stop after the chip shuts down. In about 2 days prior it killed one of my battery sets, drained them so low that even my external charger wont recognize them anymore.

So i set up a test yesterday. At 0:00 i put in a set of partially charged batteries. 3.78V charge. After 1 hour, nothing changed. But today after waking up at around 12:00 it had dropped to 3.28, so it lost about 0.50V just doing nothing.

Batterys are LG HE2s (set to GEN) and BVO is at 0.00. Clock is disabled, LSL is off. I tried to disable USB charging so i could log the draining batteries but it still charges them. So the only thing i can provide is my settings export file. [IStick TC100W Tiankay.zip](https://github.com/maelstrom2001/ArcticFox/files/801160/IStick.TC100W.Tiankay.zip)

Peace
TK

**Comment by MoDuLah** [comment]
Do you have LSL on?

**Comment by smok-e** [comment]
I never had this happening on my iStick TC100W. I'm using it with the firmeware 170214. But all updates I did never had this problem, maybe it is a hardware issue?

**Comment by Tiankay64** [comment]
It could be, but like i said i doubt it because it wasnt happening with the original eleaf 1.12 Firmware before.

Im running a new test today. I flashed the 170222 nightly yesterday and i will put some fully charged batteries into the mod to document the drain hourly by hand if it still appears with this build. I will report back with more data then later this day or tomorrow morning.

Peace
TK

**Comment by smok-e** [comment]
I would install the original eleaf firmware again and see if it doesn't have the issue. And then try again the arcticfox firmware.

**Comment by Tiankay64** [comment]
Mysterious. Wasnt happening before, but now also happens with stock firmware. So it really seems to be hardware, Case closed then

peace
TK
