### ISSUE TITLE
Vaporflask, Beyondvape, Vaponaute devices support

### ISSUE THREAD

**Issue by Presskohle** [maelstrom2001/ArcticFox#17]
Hi
I'm talking about devices produced by Wismec (all using the same chip afaik) in cooperation with some other party.

for example:
Vaporflask Classic/Lite/Stout
Beyondvape Centurion
Vaponaute La Petite Box

best regards,

**Comment by TBXin** [comment]
Hi,

Yes, we are planning to add support for third-party devices.
Everything has its time. Now we are busy doing other things ^^

**Comment by TBXin** [comment]
Done in the [ArcticFox 170103](https://github.com/maelstrom2001/ArcticFox/releases/tag/170103).

Added support (experimental, not fully tested) for:

* Reuleaux RXmini
*  VF Lite
*  VF Stout
*  VF Classic
*  BV Centurion
