### ISSUE TITLE
Increase the relax delay of preheat function

### ISSUE THREAD

**Issue by westor7** [maelstrom2001/ArcticFox#170]
Hello,

Now as i can see the limitation of the max delay for relax into the preheat function is 20-25 seconds, is there a way to make it be max to 60-90 seconds value, because 25 max is too low now.

- Thanks!

**Comment by ceinro** [comment]
He has a point ! Can be longer.

**Comment by TBXin** [comment]
Hello @westor7 

Preheat delay timer restarts each time when your are making puff >=preheat time.
In other words, usually you should not press the Fire button for the entire time of the preheat delay to again obtain preheat.

**Comment by westor7** [comment]
@TBXin Yes, but the head request here is to increase this delay value from 20-25 that is max now to 60-90.

**Comment by TBXin** [comment]
@westor7 i'am trying to understand for what reason you need so long delay.

**Comment by ceinro** [comment]
Because some coils dont cool down in 20s and preheating them will cause them to overheat as the initial temp is higher than cold temperature.

**Comment by TBXin** [comment]
@ceinro above I described how the delay is works. You can get "overheating" only if you will make puffs every 20 sec (with cooldown 20).

And i am really confused, because i use coils with resistance around 0.1-0.2 ohms (tripple staggered / stapples and so on) and even they have no problems with cool down for 20 seconds.

**Comment by westor7** [comment]
@TBXin i cannot see here why is an limitation about 25 only max seconds, why not at least 60 seconds (1min), i vape really very different way from you, and i really need a big relax at least 1 min in order to be useful for me the preheat function, i cannot see any negative action by increasing it from 25 to 60 for example.

- Thanks!

**Comment by Sanaki** [comment]
For info only (I don't use preheat), my 0.083 ohm titanium coils take 65 seconds to return from 350F to within 15% (0.095 ohms) of base resistance and 135 seconds total to drop to 0.09 ohms (still warm, but not hot). While I personally have no skin in this game, I can fully understand why longer times would be needed with heavier coils.

**Comment by westor7** [comment]
@TBXin So, will you increase the max delay limitation value from 25 to 60 or more ?

- Thanks!

**Comment by TBXin** [comment]
Will be available in the next release.

**Comment by om22** [comment]
@TBXin would it be possible to restart the counter even when puff length is under the set preheat time?

For example: I like to preheat @60W for 2-3 seconds only for the first puff so my clapton gets to temperature. After that I almost only use puffs under 2-3sec (at about 30-40w) so preheat will activate again even though I kept the coil warm with my small puffs.

**Comment by maelstrom2001** [comment]
Released.
