### ISSUE TITLE
iStick Pico 75TC clock reset

### ISSUE THREAD

**Issue by 60nine** [maelstrom2001/ArcticFox#173]
Hi... 
clock resets everytime i change the battery in the mod... (iStick Pico 75TC)

i guess it can't be fixed because there is no internal (backup) battery in the mod itself... so it would be ok to add an option to remove the clock completely... 

thanks in advance...

sincerely,
D.

**Comment by TBXin** [comment]
Hello,

You can completly disable clock in the menu. 

Menu -> Screen -> Clock: Turn off "On Main" and "Saver" options.

**Comment by 60nine** [comment]
yes... i'm stupid :D sorry...
