### ISSUE TITLE
Is Device Monitor realtime?

### ISSUE THREAD

**Issue by andreivoinea93** [maelstrom2001/ArcticFox#177]
Are the values in DM realtime, or it takes only the values at a specific interval?

If they are real time:
Is that the absolute maximum frequency at which TC calculation can be done? I highly doubt so. Not to be mean or anything, but it certainly can be improved, I'd be happy to help.
If not, are there any other hardware limitations besides the microcontroller?

If they are not realtime:
Why so? Both USB protocol (or UART) and the Device Manager are clearly capable. I know it gives no specific advantage, but if it looks prettier and you have no specific reason not to do it, why not? :D

**Comment by TBXin** [comment]
Device Monitor requests data at 10hz frequency.
I don't see any reason to do it more often.
