### ISSUE TITLE
Battery charge on Pico 75w

### ISSUE THREAD

**Issue by miasmi** [maelstrom2001/ArcticFox#179]
It's impossible to disable battery charge in pico 75w. The "USB Charge" box is unchecked but in the screen of the pico you can still see battery charging.

**Comment by Sonicaki** [comment]
i confirm that too. I have the same problem with the pico 75watt

**Comment by maelstrom2001** [comment]
In single battery boxes charging can not be controlled by firmware, it is always enabled.

**Comment by miasmi** [comment]
thanx!
