### ISSUE TITLE
How do you download ?

### ISSUE THREAD

**Issue by Gremdude** [maelstrom2001/ArcticFox#18]
I know I am probably going to look like an idiot but.... I can't seem to figure out how to download this! It looks like the only file available is a readme? Is this firmware not yet ready for public consumption? I know I am probably missing something really obvious.... LOL. Yeah I finally figured it out!! This firmware is amazing!!!!!!!!!!!!!!!!!!!!!

**Comment by TBXin** [comment]
He, @Gremdude 

You can always download latest release here: https://github.com/maelstrom2001/ArcticFox/releases

**Comment by Gremdude** [comment]
Thank you!!!
