### ISSUE TITLE
[Bug?] VTwo Mini incorrect resistance only at rest/during TC overshoot

### ISSUE THREAD

**Issue by robhalbert** [maelstrom2001/ArcticFox#186]
After attaching an atomizer to my VTwo Mini, arcticfox assigns a profile with correct resistance for my coil (appx. 0.27 ohm), but the live resistance display fluctuates, usually around 0.45 ohm. Immediately after firing — and also for a while if the power is set low (E.G. 1W)  — the live resistance returns to around 0.27 ohm.

Also, if the temp limit is reached in TC mode, the device disables the output and reads the coil high again, leading arcticfox to report the temp as very high and thus it does not re-enable power output for some time, if at all. This means that the TC feature does not work properly. Setting the temp limit higher than the coil can reach or setting the power low gives correct resistance/temp readings.

I have tried this on several Ni and SS316L coils, and it seems to occur with larger coils only.

I think this is a firmware issue as despite the resistance showing wrong in these cases, arcticfox always assigns the resistance correctly in the profile when a new coil is attached, so it is capable of reading it correctly.

**Comment by forkoz** [comment]
sounds like that's what happening to me. I have to frequently unscrew and re-attach when I get no power. Coil reads .42 but really it is .48. I wasn't sure if it was a bug or just a me problem.
