### ISSUE TITLE
Istick Pico Dual: "unknown device"?

### ISSUE THREAD

**Issue by rabenacht** [maelstrom2001/ArcticFox#189]
I have got a Pico Dual, which should be supported, but it is identified as "unknown device". Also there is no .xml file in "Definitions" for the pico dual. Otherwise: I flashed the Pico Dual and everything works correct as with my other mods (evic vtc mini, pico, istick 100 etc.). So I am a little bit puzzeld.

**Comment by TBXin** [comment]
Hello,

This is a known issue. 
Device name does not affect anything, just visual information on your screen.

Also you should not create issues related to the NFE in this repository.
