### ISSUE TITLE
Joyetech Cubis QCS coil in TC mode

### ISSUE THREAD

**Issue by vendeghlajos** [maelstrom2001/ArcticFox#19]
Constant error message, only power mode is usable.
0.5 Ohm SS coil is working with TC without any issue.

**Comment by maelstrom2001** [comment]
Try to disable TCR check: Main Menu -> Settings -> Expert -> ChkTCR set to Off.

**Comment by vendeghlajos** [comment]
same with TC check OFF

**Comment by TBXin** [comment]
DId you know from what material this notch coils are made?

**Comment by vendeghlajos** [comment]
SS316

**Comment by TBXin** [comment]
Any way, you can try custom TCR: 92 with this coils.

**Comment by vendeghlajos** [comment]
It is basically same as the Joyetech Notch coil. 

http://www.joyetech.com/product/notchcoiltm-0-25ohm-dl-head/

**Comment by TBXin** [comment]
> It is basically same as the Joyetech Notch coil.

You can try TFR 316L or custom TCR: 92 with this coils.

**Comment by vendeghlajos** [comment]
same error message on both. sorry to say.

**Comment by TBXin** [comment]
@vendeghlajos okay, this coils work properly with OFW ?
