### ISSUE TITLE
Cuboid not detecting on pc

### ISSUE THREAD

**Issue by myskull321** [maelstrom2001/ArcticFox#192]
Hey

So i am trying to install the software but my device is not even detecting on the joyetech firmware updater, does anyone know what might be wrong?

Thanks in advance

**Comment by TBXin** [comment]
Hello,

If you want to install ArcticFox firmware you should use NToolbox.
Here is guide: https://github.com/maelstrom2001/ArcticFox/wiki/How-to-install
