### ISSUE TITLE
Smok mod support

### ISSUE THREAD

**Issue by Maschine123** [maelstrom2001/ArcticFox#194]
Hi

I use your firmware on my iStick Pico and on my Evic vtwo and love the firmware. 
Now I bought a new Smok AL85 and want to flash ArcticFox on my Smok mod.
Are your working on firmware for this device? 
Smok Alien devices are popular and this would be very cool

Thanks

**Comment by TBXin** [comment]
Hello,

We are glad and very appreciate that you like our firmware.
But we are not going to create the firmware for Smok device.

**Comment by Maschine123** [comment]
Hmm this is sad. 
Can I ask why?

**Comment by TBXin** [comment]
We are not Smok fans ^^

Seriously speaking, imposible to port an existing firmware. Need to create a new one from scratch, and it is very complex and long task.

**Comment by Maschine123** [comment]
So a firmware for smok devices will never happen?

**Comment by TBXin** [comment]
more likely no than yes.
