### ISSUE TITLE
Screen always on while charging or on pc

### ISSUE THREAD

**Issue by GnFlala** [maelstrom2001/ArcticFox#195]
Evic vtc mini.

Is there a setting i can change so that sceen turns off after a while? I am not using screen saver or clocks.

**Comment by TBXin** [comment]
Hello,

There are no such setting. At this point you can turn on "stealth mode" while you are charging your device via USB. When "stealth mode" is enabled the screen will be turned off almost always.

**Comment by GnFlala** [comment]
Thanks you :D
