### ISSUE TITLE
Avatar Reverse Charging Adapter support

### ISSUE THREAD

**Issue by Madad1996** [maelstrom2001/ArcticFox#197]
Is it possible to add the RC Charger support to Devices like the RX200?

**Comment by StillVoidingWarranties** [comment]
The Eleaf Pico Dual and the Joyetech Primo also have this feature.

**Comment by Madad1996** [comment]
So it is Software Side or Hardware?

**Comment by ZenFree** [comment]
Yeah, firmware support for Avatar Charging Adapter would be awesome!

**Comment by Ersad26** [comment]
This would be great.

**Comment by maelstrom2001** [comment]
#93
