### ISSUE TITLE
[Request] Info Page

### ISSUE THREAD

**Issue by fuedhdf** [maelstrom2001/ArcticFox#2]
Hi! 
Your work is awesome! Is it possible to add a Infopage like the about page in the menu to show system informations like Bat1,2,3 level, puff count, board temp and so on ?
All informations on one page would be nice.

Greets!

**Comment by TBXin** [comment]
We thought in this direction.
In other words, we have plans to make info screen.

**Comment by TBXin** [comment]
Done in latest release.

![](http://i.imgur.com/2QoKfkX.png)
