### ISSUE TITLE
Request: Configure at what voltage to stop charging and showing low battery.

### ISSUE THREAD

**Issue by snigel** [maelstrom2001/ArcticFox#203]
I don't need to fully charge my device all the way to 4.2v.
Going for something like 4v or 4.1v prolongs the life of the battery.

Currently I do this by simply pulling the plug when it's getting close to a voltage of choice.
For the same reason I try to not fully discharge my device.

It would be really good if this could be a configurable parameter, so I could reduce the voltage considered as max charge and increase the voltage when it's considered empty.

**Comment by TBXin** [comment]
https://github.com/maelstrom2001/ArcticFox/issues/202#issuecomment-285049114
