### ISSUE TITLE
eleaf pico not locking keys

### ISSUE THREAD

**Issue by archphile** [maelstrom2001/ArcticFox#204]
Hi all,

I have been using pico with latest arcticfox and it does not lock the keys when - and + are pressed together. It shows that the keys are locked but is still can press the power button and vape like it's unlocked.

Regards,

Michael

**Comment by TBXin** [comment]
Hello,

Key lock has exactly the same behavior as in the original firmware.
Key lock blocks increment/decrement of the power/temperature (+- button), not fire button.

**Comment by archphile** [comment]
I am sorry. I ve never used pico without arcticfox and I did not know it.

However it would be really useful if power button was locked too so that it would be easy to put it in the pocket etc.

Thanks,
Michael

**Comment by TBXin** [comment]
@archphile 

No problem,

You can press fire button 5 times to turn on/off device.
