### ISSUE TITLE
Lock resistance shortcut

### ISSUE THREAD

**Issue by ZenFree** [maelstrom2001/ArcticFox#207]
If one changes both lines to other values then "Resistance" under Layout / Small Screen then there is no way to lock/unlock the resistance on the mod itself (it's possible to trick the mod to lock the resistance if manually change Ohm value but no way to unlock it without a computer). The possible solution could be an option under "Controls" to lock/unlock resistance with specified amount of Fire button clicks. 

It would also be great if one could customize what happens when press button combinations like Fire+Plus and Fire+Minus the same way as it's done for Fire button.

**Comment by maelstrom2001** [comment]
Released.
