### ISSUE TITLE
Weak battery resets mod at high wattage (Evic VTC Mini)

### ISSUE THREAD

**Issue by phildabill** [maelstrom2001/ArcticFox#208]
Hello,

I sometimes use a VTC mini or DNA device to test fake HG2s.  Set the device to 75W with a 0.2ohm coil and fire away. If it can handle 5x 6-7seconds pulls the battery is most likely not a fake.

After flashing to ArticFox, The device resets and gives an "atomizer low" message when running this test with a fake HG2. Using the same atty/battery on an unflashed VTC Mini gives the "weak battery" error.

I assume there is a bug somewhere causing this? Or is this by design?

Thanks

**Comment by traviswparker** [comment]
That's not a reliable test of anything. 

My VTC Mini will always reset if the battery voltage sags below 3.3v, and that is with a genuine HG2 or 25R. It's a hardware limitation. The chip needs 3.3v to run. 

AFox might be applying higher initial power and pulling the battery down too hard.

**Comment by phildabill** [comment]
kk..makes sense. Why is AF pulling more power initially then?

**Comment by TBXin** [comment]
Firmware will work until battery voltage is higher than ~2.8 volts under load.
