### ISSUE TITLE
clock bug

### ISSUE THREAD

**Issue by mirko93s** [maelstrom2001/ArcticFox#209]
I have an evic vtwo mini, with rtc chip...
with 170201 firmware... I set clock often, but every next day the clock is wrong

**Comment by TBXin** [comment]
Turn on X32.

**Comment by mirko93s** [comment]
Thanks for answer... I activated x32 yesterday... after 15 hours the clock is about 17 minutes in adavance...

Inviato da iPhone

Il giorno 11 mar 2017, alle ore 16:58, ReikoKitsune <notifications@github.com<mailto:notifications@github.com>> ha scritto:


Turn on X32.

**Comment by TBXin** [comment]
Bad for you. Most likely your device has a defective RTC-module and we can't fix this programmatically.

**Comment by mirko93s** [comment]
With original fw and with older arcticfox fw it works good...

Inviato da iPhone

Il giorno 12 mar 2017, alle ore 08:14, ReikoKitsune <notifications@github.com<mailto:notifications@github.com>> ha scritto:


Bad for you. Most likely your device has a defective RTC-module and we can't fix this programmatically.

**Comment by TBXin** [comment]
We have not changed anything in the RTC.
If it worked before it should now.

You can try to reset your device settings, restart device and configure it again from scratch.

**Comment by mirko93s** [comment]
Maybe I have to adjust clock speed... ehat value i should set?

Inviato da iPhone

Il giorno 12 mar 2017, alle ore 08:26, ReikoKitsune <notifications@github.com<mailto:notifications@github.com>> ha scritto:


We have not changed anything in the RTC.
If it worked before it should now.

You can try to reset your device settings, restart device and configure it again from scratch.

**Comment by TBXin** [comment]
May be you have LSL on earlier?

**Comment by mirko93s** [comment]
I disabled lsl beacuse vtwo mini has rtc crystal... if i am not mistaking... how can i set rtc speed properly?

Inviato da iPhone

Il giorno 12 mar 2017, alle ore 08:29, ReikoKitsune <notifications@github.com<mailto:notifications@github.com>> ha scritto:


May be you have LSL on earlier?

**Comment by TBXin** [comment]
RTC Speed does not affect anything when X32 is ON or LSL is ON.

X32 = On - time is calculated by integrated RTC Module.
LSL = On - time is calculated by primary processor.

X32 = Off, LSL = Off - time is calculated in standby mode by LIRC module, for which is RTC Speed is designed.

**Comment by mirko93s** [comment]
Ok thanks for explanation... I try to reset my device... Thank you

Inviato da iPhone

Il giorno 12 mar 2017, alle ore 08:45, ReikoKitsune <notifications@github.com<mailto:notifications@github.com>> ha scritto:


RTC Speed does not affect anything when X32 is ON or LSL is ON.

X32 = On - time is calculated by integrated RTC Module.
LSL = On - time is calculated by primary processor.

X32 = Off, LSL = Off - time is calculated in standby mode by LIRC module, for which is RTC Speed is designed.

**Comment by maelstrom2001** [comment]
@mirko93s Enter Main Menu -> Settings -> RTC -> RTC Speed. Normally, if RTC using hardware 32768 crystal there should be label "X32 On" instead of value. If you see there some value such as 33800, it indicates that firmware was failed to initialize hardware module, something goes wrong and oscillator was switched to LIRC. In this case RTC will not be accurate, and the solution is to use software correction with forcing X32 to Off and LSL to On. Or try to reset box, flash stock firmware and go back to AF, reinstall battery and play with settings while you get "X32 On" in RTC Speed dialog - that way you'll get full hardware support.

**Comment by mirko93s** [comment]
Thanks a lot! I'll try this solution and I'll tell you if i solve problem... have a nice day

Inviato da iPhone

Il giorno 12 mar 2017, alle ore 13:40, maelstrom2001 <notifications@github.com<mailto:notifications@github.com>> ha scritto:


@mirko93s<https://github.com/mirko93s> Enter Main Menu -> Settings -> RTC -> RTC Speed. Normally, if RTC using hardware 32768 crystal there should be label "X32 On" instead of value. If you see there some value such as 33800, it indicates that firmware was failed to initialize hardware module, something goes wrong and oscillator was switched to LIRC. In this case RTC will not be accurate, and the solution is to use software correction with forcing X32 to Off and LSL to On. Or try to reset box, flash stock firmware and go back to AF, reinstall battery and play with settings while you get "X32 On" in RTC Speed dialog - that way you'll get full hardware support.

**Comment by maelstrom2001** [comment]
@mirko93s And a little addition to previous post :) 
Try to set LSL = Off, X32 = On in Expert Menu, select Exit item, wait for 10 seconds to be sure that settings was written to dataflash, and remove battery. Wait about 2 minutes, install battery and go to Expert Settings.
If you find that X32 option goes to Off that is the sign that hardware was not initialized properly.
If this option will remain On after power-on - good news, hardware RTC is working properly now.

**Comment by mirko93s** [comment]
Ok I set x32 on, lsl off, removed battery, wait 2 minutes, insert battery... now in rtc speed it says x32 on... I think it works good now... Thanks for help man!

Inviato da iPhone

Il giorno 12 mar 2017, alle ore 18:52, maelstrom2001 <notifications@github.com<mailto:notifications@github.com>> ha scritto:


@mirko93s<https://github.com/mirko93s> And a little addition to previous post :)
Try to set LSL = Off, X32 = On in Expert Menu, select Exit item, wait for 10 seconds to be sure that settings was written to dataflash, and remove battery. Wait about 2 minutes, install battery and go to Expert Settings.
If you find that X32 option goes to Off that is the sign that hardware was not initialized properly.
If this option will remain On after power-on - good news, hardware RTC is working properly now.

**Comment by maelstrom2001** [comment]
> now in rtc speed it says x32 on

Yep, now the clock should be accurate as in stock firmware. Cheers! :)
