### ISSUE TITLE
[Suggestion] Puff counter digits number

### ISSUE THREAD

**Issue by vendeghlajos** [maelstrom2001/ArcticFox#21]
When not needed, it could be only 1-2-3 digit visible without the first zeros. I mean 00200 would be displayed as 200. Thx.

**Comment by TBXin** [comment]
Done in the [ArcticFox 170103](https://github.com/maelstrom2001/ArcticFox/releases/tag/170103).

You can switch between two styles: seconds (without zeros) and H:MM:SS.
To change style you should use [NFE Toolbox](https://github.com/TBXin/NFirmwareEditor/releases/tag/6.4).

**Comment by vendeghlajos** [comment]
sorry, but my idea was not about the time, but about the puff numbers. probably you closed this accidentally.

**Comment by TBXin** [comment]
I don't think so ^^

![](http://i.imgur.com/sUrkZta.png)

**Comment by vendeghlajos** [comment]
achhhh, i updated the mod. thank you NICE!!!
