### ISSUE TITLE
Dry Cotton

### ISSUE THREAD

**Issue by Prole97** [maelstrom2001/ArcticFox#210]
You can't improve on the firmware the advice "Dry cotton" when the ohm of the coil go up (kanthal/tc)

**Comment by ZenFree** [comment]
Are you asking for temperature control for Kanthal coils?

**Comment by Prole97** [comment]
Nope, i ask for an advice when the cotton is dry, if the cotton is dry the ohm of the coil grown up

Inviato dal mio telefono Windows 10

Da: ZenFree<mailto:notifications@github.com>
Inviato: domenica 12 marzo 2017 01:29
A: maelstrom2001/ArcticFox<mailto:ArcticFox@noreply.github.com>
Cc: Prole97<mailto:enzozizza@hotmail.it>; Author<mailto:author@noreply.github.com>
Oggetto: Re: [maelstrom2001/ArcticFox] Dry Cotton (#210)


Are you asking for temperature control for Kanthal coils?

**Comment by ZenFree** [comment]
The coil resistance increase is directly proportional to the coil temperature. When coil is saturated then some amount of power is used to evaporate the liquid which slows down the rise of coil temperature. On the dry coil all power is used to heat the coil so the coil is warming up faster. TC mode controls how much resistance increase to allow. It approximates temperature based on TCR curve. The Kanthal coil changes resistance too little for TC to calculate temperature.
Does it answer your question?

**Comment by Prole97** [comment]
Yes, thank you

Inviato dal mio telefono Windows 10

Da: ZenFree<mailto:notifications@github.com>
Inviato: domenica 12 marzo 2017 04:19
A: maelstrom2001/ArcticFox<mailto:ArcticFox@noreply.github.com>
Cc: Prole97<mailto:enzozizza@hotmail.it>; Author<mailto:author@noreply.github.com>
Oggetto: Re: [maelstrom2001/ArcticFox] Dry Cotton (#210)


The coil resistance increase is directly proportional to the coil temperature. When coil is saturated then some amount of power is used to evaporate the liquid which slows down the rise of coil temperature. On the dry coil all power is used to heat the coil so the coil is warming up faster. TC mode controls how much resistance increase to allow. It approximates temperature based on TCR curve. The Kanthal coil changes resistance too little for TC to calculate temperature.
Does it answer your question?

**Comment by StillVoidingWarranties** [comment]
Mods cannot measure humidity of the wick or temperature of the coil directly, they do not have sensors for that. They try to calculate the coil's temperature from its resistance - if it is made of a material which has a negative temperature coefficient (which kanthal does not).

**Comment by Sanaki** [comment]
> if it is made of a material which has a negative temperature coefficient (which kanthal does not).

For the sake of accuracy (though it changes nothing for these purposes), kanthal does indeed have a measurable TCR. It's just so obscenely small that as of yet -no one- has managed to make an affordable and compact way to actually read it.
