### ISSUE TITLE
Eleaf pico dual

### ISSUE THREAD

**Issue by Tomozaki123** [maelstrom2001/ArcticFox#214]
Hi.
Great frimware, but in pico dual in wattage mode you can't set w over 100. I have pico dual and rt 25 or melo 300.

**Comment by maelstrom2001** [comment]
What resistance does the atomizer have?

**Comment by StillVoidingWarranties** [comment]
Cannot confirm (170222), my Pico Dual lets me set 168 W on a 0.48 Ohm coil.

**Comment by Tomozaki123** [comment]
I have Eleaf ERLQ 0.15Ohm coil and Eleaf RT 25 ( or Eleaf Melo 300) atomizer.

**Comment by TBXin** [comment]
@Tomozaki123 you can't set more that ~100W for 0.15 Ohms coil because of 25A limitations on the PCB.
To get more power you need to increase your coils resistance.

Here screenshot of the Ohms law calculator:
![](http://i.imgur.com/7LkGKdE.png)

**Comment by maelstrom2001** [comment]
@Tomozaki123 update firmware to [ the latest nightly](https://github.com/maelstrom2001/ArcticFox/wiki/Changelog)

**Comment by Tomozaki123** [comment]
Yes, by ohm law. But on offical firmware i can set up to 200W, on specifications it's written that Pico Dual is capeble of 200W/50A?

**Comment by Tomozaki123** [comment]
I update firmware, now it work's. Thank you for help. You are doing good work.
