### ISSUE TITLE
Change layout when firing?

### ISSUE THREAD

**Issue by loverthehater** [maelstrom2001/ArcticFox#219]
I think it would be cool if I could see the volts when I'm setting wattage and then see the amperage when I'm firing it, both on one line while I can see the battery percentage on the other. In my example, I'm talking about the "Small Screen" layout, but I feel like it would be helpful to anybody using the firmware. I can live without it, but I just thought it would be a neat suggestion.

**Comment by maelstrom2001** [comment]
#67
