### ISSUE TITLE
puff counter auto reset - every morning

### ISSUE THREAD

**Issue by vendeghlajos** [maelstrom2001/ArcticFox#22]
Hello, 
In expert mode, I switched on the RCOBC.
Randomly I get the possibility to reset the puff counter on the main screen.(keep - reset option is there)
can you explain, how this works? It is there any key combination to get into the puff counter reset?
RECOMMENDATION: I am using the counter for daily tracking, would be perfect, some auto-reset option, for example, every morning at 6:00 a.m.
thx!
Lajos

**Comment by TBXin** [comment]
Hello,

RCOBC means Reset Counters On Battery Change.
Dialog will appear when you device is turned on after you insert battery (every cold startup).

**Comment by vendeghlajos** [comment]
thx, now it is clear. Probably I disconnecting the battery time to time.
Could you consider in the next releases about the daily auto reset option?

**Comment by TBXin** [comment]
If you want to reset the counters - do it manually.
We will not implement automatic actions, tied to the time.

**Comment by vendeghlajos** [comment]
Sad to hear...I think many users would appreciate this option, and no firmware offer this option.
OTHER OPTION: most of the users are fully charging his devices during the night - when 100% battery level reached, after unplugging from the charger could be offered the option of the auto reset.
I do not see the point, why after the battery disconnection is the reset option offered. Many devices has a built-in battery.

**Comment by blitzu** [comment]
I want this function too

**Comment by febs** [comment]
It would also amazing to have separate puff counts per profile.
This way I could count how many puffs I had on my Nautilus and how many on my TFV8.

**Comment by maelstrom2001** [comment]
@febs 
> separate puff counts per profile

Sorry, it's cool feature but it will be just wasting of EEPROM space and, which is more critical - its lifetime. Nothing personal, just the reality :)

**Comment by vendeghlajos** [comment]
but the possibility of  the "morning auto reset" or the " auto reset after the battery is fully charged" feature you found acceptable? ;-)

**Comment by maelstrom2001** [comment]
@vendeghlajos At at this moment can not say exactly when it will be implemented, we have a huge todo list

**Comment by vendeghlajos** [comment]
Thank you!
PS: would be good to share with us your plans - what we could expect in the exciting future!

**Comment by TBXin** [comment]
You can follow our twitter account to get informed about updates and about announcements.
https://twitter.com/NfeTeam
