### ISSUE TITLE
eleaf ipower clock

### ISSUE THREAD

**Issue by muddyek** [maelstrom2001/ArcticFox#220]
hi. my clock keeps getting out by 5min after 18hours, what speed should i adjust this to and should i turn on lsl or xr32 or what? any help would be much appreciated
firmware is 170201

**Comment by maelstrom2001** [comment]
Set options:
X32 = Off
LSL = On
with NToolbox or via Expert menu, wait about 10 seconds and restart iPower by pressing Reset button.

**Comment by adem4ik** [comment]
Will those options work for Eleaf iStick Pico too? I have same problem with my clock.

**Comment by maelstrom2001** [comment]
These settings are applicable to any mod without full hardware RTC support.

**Comment by adem4ik** [comment]
Thanks for anwser!
