### ISSUE TITLE
Nightly Builds unavailable on DropBox ?

### ISSUE THREAD

**Issue by FrankBKK** [maelstrom2001/ArcticFox#221]
Is there another link available for the latest builds ? 

https://www.dropbox.com

Error (429)
This account's links are generating too much traffic and have been temporarily disabled!

**Comment by GnFlala** [comment]
i have 170222 if you need it tell me to generate a link for you

**Comment by TBXin** [comment]
We will reupload nightly builds today. Stay tuned.

**Comment by TBXin** [comment]
Done. Also we are fixed links here https://github.com/maelstrom2001/ArcticFox/wiki/Changelog

**Comment by FrankBKK** [comment]
cool, thanks !
