### ISSUE TITLE
Eleaf Pico Dual Cant set more watts then 93.8

### ISSUE THREAD

**Issue by GFSNinja** [maelstrom2001/ArcticFox#222]
I have this problem with my pico dual that when i instal arctic fox i cant set more watts then 93.8 i dont know why but when i instal firmware its says Unknown device. 
Please reply fast i realy want my 200 watts with arctic fox.

**Comment by maelstrom2001** [comment]
Update firmware and NToolbox to [the latest nightly](https://github.com/maelstrom2001/ArcticFox/wiki/Changelog).

**Comment by GFSNinja** [comment]
i have
![screenshot_3](https://cloud.githubusercontent.com/assets/26550156/24110263/4b43836e-0d93-11e7-930e-11041457693d.png)
![screenshot_3](https://cloud.githubusercontent.com/assets/26550156/24110274/53e6c06c-0d93-11e7-9584-a490e4a8a4be.png)

**Comment by GFSNinja** [comment]
I have
![screenshot_2](https://cloud.githubusercontent.com/assets/26550156/24110292/620eced2-0d93-11e7-8bb6-0e0c6ab3602b.png)
![screenshot_3](https://cloud.githubusercontent.com/assets/26550156/24110297/63c11e7e-0d93-11e7-872c-3d2d801ee66f.png)

**Comment by GFSNinja** [comment]
Ty man you are the best.
