### ISSUE TITLE
How to install the FW on Joyetech Primo?

### ISSUE THREAD

**Issue by javak810i** [maelstrom2001/ArcticFox#224]
Hey, I wanted to install the latest 222 release on my Joytech Primo with 4.05 stock FW via NFE toolbox 1.5 and I'm getting the "FW not supported for this device" error. Any help?

**Comment by ZenFree** [comment]
Did you try to install 170222 firmware and latest NFE build?
https://github.com/maelstrom2001/ArcticFox/wiki/Changelog
https://ci.appveyor.com/project/TBXin/NFirmwareEditor/branch/master/artifacts

**Comment by javak810i** [comment]
No I did it with 6.5.0
should the one you posted work?

**Comment by ZenFree** [comment]
I don't have Primo to test, but new NFE version may help based on the error you have received. They just recently added support for Primo which wasn't available in previous versions.
