### ISSUE TITLE
Can't change controls for Pico

### ISSUE THREAD

**Issue by tanked-kiwi** [maelstrom2001/ArcticFox#231]
Hi,

First off, I'm loving this firmware. Keep up the great work.

The issue i'm having is with changing the controls for the menu on the pico. Default is 2 clicks smart on/off, 3 clicks do nothing, 4 clicks change profile. I need to change this as I can't edit or access the menu unless I plug into a pc. Everything else is working fine, but every time i change this in the arctixfox config it doesn't stick.

Cheers

**Comment by tanked-kiwi** [comment]
Nevermind, I found out how to change this through the mod itself, although still a minor issue with the config tool.

**Comment by espezetka** [comment]
Fire and plus :D
