### ISSUE TITLE
a big error

### ISSUE THREAD

**Issue by tiryaki92** [maelstrom2001/ArcticFox#233]
I use your hello software. However, sometimes I prefer myevic software. Why do not you answer myvic why you developed in conjunction with ClockSelect is not updating @maelstrom2001

**Comment by TBXin** [comment]
In english plz.

**Comment by tiryaki92** [comment]
mean, why is not your other application Myevic being updated

**Comment by TBXin** [comment]
This is ArcticFox repository, not myEvic.
