### ISSUE TITLE
Is there a compatible build that works with Wismec Predator?

### ISSUE THREAD

**Issue by ZenFree** [maelstrom2001/ArcticFox#234]
I just got Predator and would love to install ArcticFox on it. Is there a build that currently supports this mod? 

I did see a closed issue 185, but even version 170324 is saying it's not compatible with this device. I tried it with NFirmware Editor nightly build version 6.5.104.

https://github.com/maelstrom2001/ArcticFox/issues/185

**Comment by maelstrom2001** [comment]
> Is there a build that currently supports this mod?

Hello! Yes, we working on Predator's support, ATM it is implemented and being tested, but it is bit early for publishing.

**Comment by ZenFree** [comment]
Thank you! Please let me know if you would like me to test it when it's ready.

**Comment by maelstrom2001** [comment]
Thanks! When build will be available, will reopen #185 to keep all development stages together in one issue :)
