### ISSUE TITLE
I can provide CN.LPACK.TXT, how can I provide to the author? (nfetool)

### ISSUE THREAD

**Issue by vojaly** [maelstrom2001/ArcticFox#237]
I can provide CN.LPACK.TXT, how can I provide to the author? (nfetool)

**Comment by TBXin** [comment]
Hello,

I read your message on the forum, but i can't reply because your account was banned.

Sure, you can provide CN localization for the NToolbox, but better do it here: 

https://github.com/TBXin/NFirmwareEditor/issues
