### ISSUE TITLE
Possibility of supporting SMOK XCube Ultra?

### ISSUE THREAD

**Issue by ONDRA5** [maelstrom2001/ArcticFox#24]
Hello, is there a possibility of supporting SMOK XCube Ultra?
I'm in love with your's FW, I have used it for a while of my friend's RX2/3 and it was like another universe :)
And the FW on XCube Ultra is so screwed up :(
You can't even set Wattage in TC mode...
Looking forward to your answer.
Your's fan

**Comment by maelstrom2001** [comment]
Sorry, no. This firmware will never support Smoktech products.
