### ISSUE TITLE
Rx200s battery

### ISSUE THREAD

**Issue by pikachukaki** [maelstrom2001/ArcticFox#248]
Im using the latest release and i have 3 lg hg2 batteries in the mod.
I use the hg2 profile in battery and enable battery percentage with the windows app but the indicator show 80% from the 1st puff.

With the GEN profile it goes to 95% which seems normal as i use the mod a bit!

**Comment by maelstrom2001** [comment]
HG2 profile:

![](http://i.imgur.com/W8NeMp9.png)

GEN profile:

![](http://i.imgur.com/uLscDlS.png)


I think battery voltage drops to about 4,02..4,05 volts after puff, and you can see percentage difference between profiles. If you want to have precise % calculation you have to make your own profile, 'cause it will be depended on number of battery cycles, your vaping power, resistance of atomizer etc.

**Comment by pikachukaki** [comment]
I found some profiles and edit them to be imported to your app
![screenshot_1](https://cloud.githubusercontent.com/assets/3009586/24587275/f34344f0-17bb-11e7-8d04-2ea64ac3bc73.png)
although the values had to be edited cause your using only two decimals

**Comment by docdeath** [comment]
where do i find discharge profiles  in arcticfox ?

**Comment by pikachukaki** [comment]
In windows app In advance change the battery profile to custom and then edit them.

**Comment by docdeath** [comment]
thanks did not know it was hiding there  lol

**Comment by pikachukaki** [comment]
Me neither but when i saw the pictures i have to look for it!
