### ISSUE TITLE
Wismec PREDATOR 228 Support

### ISSUE THREAD

**Issue by MicheleLynnBass** [maelstrom2001/ArcticFox#249]
Looking forward to picking up one of these...but I'll wait till I can upload ArticFox to it.

@maelstrom2001 here's the firmware for it: http://www.wismec.com/software/wismec-tc-software-for-upgrading-predator-228/

Thank you for all your hard work!

~ michele

**Comment by maelstrom2001** [comment]
#246 #234 #185 
Stay tuned :)
