### ISSUE TITLE
Wismec Predator 228

### ISSUE THREAD

**Issue by DamnMyEyes** [maelstrom2001/ArcticFox#250]
Hello.  First I am requesting that the Predator 228 get added as a supported device for ArcticFox.  Second, is there a way to force the ArcticFox firmware into the Predator?  It currently just says unsupported device but I believe that it has either the same or a very similar chip as the RX300.

Thank you!

**Comment by maelstrom2001** [comment]
#249 #246 #234 #185 
Work in progress ^^
