### ISSUE TITLE
Wismec Predator support

### ISSUE THREAD

**Issue by st0neh** [maelstrom2001/ArcticFox#252]
Hi,

Apologies if this is already being worked on, but is there any chance of support for the new Wismec Predator?

Here's the product ID, official firmware link, and a dump of the firmware from my device if it helps.

 ![](http://i.imgur.com/9VM1Ir7.png)

http://www.wismec.com/software/wismec-tc-software-for-upgrading-predator-228/

https://drive.google.com/open?id=0B_qB8TxTsglXUGtPNGZpWEVaLVE

**Comment by maelstrom2001** [comment]
#250 #249 #246 #234 #185
Yes, it will be supported, work in progress.
