### ISSUE TITLE
Wismec predator support?

### ISSUE THREAD

**Issue by danielthelad** [maelstrom2001/ArcticFox#255]
Would this firmware be updated to support the Wismec predator as it's basically the same firmware as the RX300 just with a 2 battery configuration instead of 4?

**Comment by TBXin** [comment]
Realy?

#252 #250 #249 #246 #234 #185

![](http://i.imgur.com/TSf1kTL.png)

**Comment by danielthelad** [comment]
Okay, okay. I'm new to the site and didn't know it was in the closed section. Didn't see it in open.
