### ISSUE TITLE
RX300 400W output

### ISSUE THREAD

**Issue by maddpiratekidd** [maelstrom2001/ArcticFox#257]
Increase the max output for the RX300 to 400Watts as per official firmware.

**Comment by ozomax1997** [comment]
would love this as ive upgraded to the new firmware but my screens are too dim as i have coloured films over the displays on both of my RX300's

**Comment by semarx300** [comment]
rx300 400w please

**Comment by TBXin** [comment]
No problem. We will update the maximum power for release version of the AF.

**Comment by RX300N** [comment]
Yeah - even though it is practically nonsense, it would be great to have Ferrari with WIsmec logo LOL.

**Comment by TBXin** [comment]
> it would be great to have Ferrari with WIsmec logo LOL.

and 1500 watts of output power ^^

**Comment by docdeath** [comment]
400w lol really  going to do cheese  toasty on mine now  f##k the vapeing lol   rx300 owner as well

**Comment by TheSpiritof69** [comment]
Guys, this is an issue tracker, not a forum.

**Comment by Madad1996** [comment]
We need an english forum.

**Comment by maelstrom2001** [comment]
Released.
