### ISSUE TITLE
.bin encoding/packaging

### ISSUE THREAD

**Issue by Mar99v** [maelstrom2001/ArcticFox#260]
How are the firmware .bin archives packaged, i am a hobbyist tinkerer/hacker and have been having trouble getting anything out of the Rx200 firmware bin and would greatly appreciate if you could shine some light on this.

**Comment by smok-e** [comment]
didn't you try the NFirmwareEditor?
you can load and edit the .bin with it.

**Comment by TBXin** [comment]
.bin file is a compiled from sources (C-language) binary file.
