### ISSUE TITLE
charge screen on multibatt boxes

### ISSUE THREAD

**Issue by BadgerAAV** [maelstrom2001/ArcticFox#262]
Screen charging in multi-battery boxes is not as readable as in the firmware myevic. Can u make a multi-line output battery charge for better readability?

ArcticFox FW - ![screen 1](https://cloud.githubusercontent.com/assets/18073910/24828488/f46f9536-1c66-11e7-963c-2b8071fef284.png) Myevic FW - ![2](https://cloud.githubusercontent.com/assets/18073910/24828490/f8bc4058-1c66-11e7-8cfe-96c6a7c29757.png)
When all the batteries in one line - it is very difficult to estimate their charge.

**Comment by maelstrom2001** [comment]
![](http://i.imgur.com/aQVoiqI.png)

Will be included to upcoming release.

**Comment by maelstrom2001** [comment]
Released.
