### ISSUE TITLE
Info Screen temperature units C° / F°

### ISSUE THREAD

**Issue by MicheleLynnBass** [maelstrom2001/ArcticFox#266]
It would be a nice option/feature to be able to switch C° to F° for board temps.

**Comment by TBXin** [comment]
Board temperature units depends on the selected units in the TC mode.

**Comment by MicheleLynnBass** [comment]
To clarify, I mean on the "Info" screen.

**Comment by TBXin** [comment]
Will fix this issue in the next release.

**Comment by maelstrom2001** [comment]
Released.

**Comment by MicheleLynnBass** [comment]
I just updated to the new version of the software and on the info screen I can't figure out how to change the C° to F°.  Please help.

**Comment by TheSpiritof69** [comment]
Just scroll over your current range and scroll once more.

At 200°F press down once to reach 315°C and vice versa.

**Comment by MicheleLynnBass** [comment]
That's for temperature control, I started this thread for the "Info" screen and requested an option to be able to set the board temp reading to either C° or F°.  This has nothing to do with temp control profiles.

**Comment by TheSpiritof69** [comment]
Changing it in Temp Mode changes it for the Info screen as well.

**Comment by MicheleLynnBass** [comment]
Ah...thanks so much!!!  Working now. :)
