### ISSUE TITLE
[Question] Logo Upload

### ISSUE THREAD

**Issue by meehr** [maelstrom2001/ArcticFox#27]
Hi, I find in the new version no possibility to load a logo to the box.

Where did it go?

Thanks for the software.

**Comment by maelstrom2001** [comment]
Use [NFirmwareEditor](https://github.com/TBXin/NFirmwareEditor) Updater to upload Logo:
![](http://i.imgur.com/LIVSvv6.png)

**Comment by meehr** [comment]
Thank you. I have used the false Programm ;) You are my Hero
