### ISSUE TITLE
rx200s my pc is not reading it any more

### ISSUE THREAD

**Issue by sabbagh21** [maelstrom2001/ArcticFox#272]
every thing was fine i downloaded the firmware connected the rx200s to the pc and it was successfully installed,the problem is the next time i tried to reconnect  it again the pc doesn't recognize it !! it's only showing that it's charging on it's screen but nothing else..
ps: i tried two different laptops and different usb cables and still not working
i need help please

**Comment by TBXin** [comment]
What kind of software did not recognize your device?
Did you hear typical sound when connecting device to the PC?
What firmware are you using?
Device still working fine(except USB) ?

**Comment by sabbagh21** [comment]
windows 10, no no voices at all it's just showing that it is charging and yes it's working perfectly except for the usb

**Comment by sabbagh21** [comment]
and the firmware is 170201

**Comment by maelstrom2001** [comment]
Try to connect box to PC in recovery mode: remove batteries, press and hold plus button and plug USB in. Box should be detected by PC, if not - check USB and cables again.

**Comment by sabbagh21** [comment]
Well I tried to do that but still not working
Could it be possible that the device's USB port defected?
Thanks in advance

**Comment by TBXin** [comment]
Yes, probably this is a hardware issue.
Try gently to clean USB connector on the device. May be some kind of dust in.

**Comment by sabbagh21** [comment]
Alright thanks guys

**Comment by sabbagh21** [comment]
Hello there ..guys i tried everything different connectors cleaned the USB socket and nothing happens.At first i thought it was the USB port that is defected or broken so i went to an expert to fix it and reinstall a new one,he checked it and said that i can put you a new socket but i think that its not the USB socket's problem it's a software's problem!! by the way it sometimes reconnect to the pc but most of the time it doesn't and when it did i uploaded wismec's firmware and also that didn't help reconnecting to the pc. Guys please i need help really i did everything but nothing worked!!
Thanks in advance

**Comment by maelstrom2001** [comment]
Hello! If your box is not detected by PC in recovery mode (without batteries and pressed + button while connecting) we can not help, 'cause it is hardware issue. In recovery mode box loading write protected part of ROM which is not modified by AF firmware.

**Comment by sabbagh21** [comment]
thank you so much for the fast reply. but do you think if i change the usb socket it might work properly?

**Comment by maelstrom2001** [comment]
Before replacing socket, check it, if it looks undamaged perhaps it will be enough to resolder it. If that does not fix problem, check tracks to MCU.

**Comment by ZenFree** [comment]
@sabbagh21 You or your tech body can use Ohmmeter to check USB connection.
