### ISSUE TITLE
[Question] Default settings on clock are unstable? (Wismec 2/3 and iStick Pico)

### ISSUE THREAD

**Issue by CasperCrasher** [maelstrom2001/ArcticFox#275]
Good morning,
i've tried to adjust clock speed via RTC, enabling LSL, X32, but nothing,
Can someone explain to me how to adjust clock speed on my iStick Pico 75W and my Wismec 2/3??

**Comment by TBXin** [comment]
1. X32 = Off;
2. LSL = On;
3. Set correct time;
4. ???
5. Profit;

Note:
Each time after batteries replacing you need to set correct time.
Both your devices does not have appropriate X32 RTC module therefore the time is calculated by the main CPU.

**Comment by maelstrom2001** [comment]
#220
