### ISSUE TITLE
Not an Issue..

### ISSUE THREAD

**Issue by MYWARUK** [maelstrom2001/ArcticFox#276]
Sorry its not an issue, but iv been asked by a few people if A.F will be ported to the Wismec Predator at all please?

Thanks!

**Comment by TheSpiritof69** [comment]
https://github.com/maelstrom2001/ArcticFox/issues/256

**Comment by MYWARUK** [comment]
Sorry, I dont know my way around Github.
But thanks for informing me, didnt know it had been asked so many times, sorry for wasting your time.
