### ISSUE TITLE
coil fixing in wv mode

### ISSUE THREAD

**Issue by sigaraci** [maelstrom2001/ArcticFox#281]
First of all, congratulations on your excellent work. You are excellent people.

This is not fixed when I try to fix ohm value in watt mode. When I come to the main page, it turns back.

**Comment by maelstrom2001** [comment]
> fix ohm value in watt mode

Coil resistance can not be locked in VW mode. It have a sense only for TC mode.

**Comment by sigaraci** [comment]
How could it be fixed like this smoky GX350? Did they benefit?

**Comment by sigaraci** [comment]
And my friend has been waiting for the new version. When will it come?

**Comment by maelstrom2001** [comment]
> smoky GX350

Why we talking about Smok? :) it's firmware for Joyetech devices. Coils were never locked in VW mode here :)
