### ISSUE TITLE
opening and closing logo

### ISSUE THREAD

**Issue by sigaraci** [maelstrom2001/ArcticFox#282]
Is it possible to set these logos on / off in the menu?

**Comment by maelstrom2001** [comment]
No.

**Comment by sigaraci** [comment]
why? The boot logo is slowing down the device too much. It must be simple for you

**Comment by maelstrom2001** [comment]
You can skip startup logo by single fire click. Or simply start vaping. Startup logo do not hangs device at all, it starting as usual.

**Comment by ETPNV13** [comment]
A two second logo is "slowing down the device too much"? Are you seriously that desperate to vape in a hurry?

**Comment by adzam016** [comment]
Does lock out vaping on mine but as ETPNV13 stated. Are you really that desperate? I like the logo coming up, I might forget who made this sick firmware otherwise ;-)
