### ISSUE TITLE
Change clock time

### ISSUE THREAD

**Issue by CrissJay** [maelstrom2001/ArcticFox#289]
I really don't know how to change the time on my eVic VTwo Mini. When the hour has changed to summer time on my mod i have the clock set with 1 hour differences. 
I looked in all settings and i can't found where is I can change the clock settings.

**Comment by TBXin** [comment]
Hello,

Menu -> Settings -> RTC -> Date/Time

**Comment by CrissJay** [comment]
Thank you!
