### ISSUE TITLE
low ohm safer

### ISSUE THREAD

**Issue by heru21** [maelstrom2001/ArcticFox#291]
i use ss straged fuse clapton and reach 0.08 ohm thats safe??? 
how low this frimware can handel low atomizer???
because dont see any description of the limit resistance about this frimeware

**Comment by maelstrom2001** [comment]
> **ss** straged fuse

You can use coil in TC mode with 0.05 ohms threshold.

**Comment by heru21** [comment]
okay, thanks for your answer
