### ISSUE TITLE
Just in case anybody else wants it...

### ISSUE THREAD

**Issue by ETPNV13** [maelstrom2001/ArcticFox#299]
Just something I made for my PC, in case anybody else wants it for themselves...
![polish-artist-paintings-nightmares-zdzislaw-beksinski-590065a7996d9__700](https://cloud.githubusercontent.com/assets/14185797/25584430/901af2a4-2e5b-11e7-9443-b641575af6c8.jpg)

**Comment by ctrlaltca** [comment]
Whoops, looks like you missed a "c" in ArcticFox

**Comment by ETPNV13** [comment]
Shit...I made it in the middle of the night...easy enough fix, give me a minute...

**Comment by ETPNV13** [comment]
Or maybe this...kinda going for a dreamscape...
![polish-artist-paintings-nightmares-zdzislaw-beksinski-59007807ddca4__700](https://cloud.githubusercontent.com/assets/14185797/25584555/27bd51c4-2e5c-11e7-835a-b746ac817595.jpg)

**Comment by ETPNV13** [comment]
Or in greyscale maybe...
![polish-artist-paintings-nightmares-zdzislaw-beksinski-59007807ddca4__700](https://cloud.githubusercontent.com/assets/14185797/25585054/5b99b2b0-2e5e-11e7-9042-1841350dedcd.jpg)

**Comment by ETPNV13** [comment]
And this just for giggles...
![polish-artist-paintings-nightmares-zdzislaw-beksinski-590065a575194__700](https://cloud.githubusercontent.com/assets/14185797/25585830/09d180da-2e62-11e7-889e-ce44c64a6b9e.jpg)

**Comment by smok-e** [comment]
very interesting pictures,
tho I would like something a bit less sinister ;-)
But it makes me curious how you did them.
how did you compose them?
did you digitally paint them or by hand?
Or did you take some pictures and composed them?
which software did you use? ...

**Comment by ETPNV13** [comment]
I use GIMP, which is basically free photoshop with pretty much all the same features and functionality which you can get here https://www.gimp.org/downloads/, the backgrounds are originally by a polish artist and then digitally uploaded, although I do a lot of my own work as well I just loved these paintings very much and wanted to make them my own for a desktop background, the artist is Zdzisław Beksiński and he had a "thing" for "photographing dreams" where he would paint many such things as you see above

**Comment by ETPNV13** [comment]
The pictures I uploaded are a little different than his originals and they have been resized to fit a 1920x1080 screen as well so the aspect ratio is very different from his paintings but if you have any other questions just let me know, happy to help

**Comment by ETPNV13** [comment]
Oh and if you want some cool custom fonts you can find many for free at http://www.dafont.com/ which is where I get most of my fonts from for doing custom stuff and the font I used here is called "flesh wound"

**Comment by ETPNV13** [comment]
@smok-e Maybe this is more your style?
![wolfs-rain-wallpaper-560x310](https://cloud.githubusercontent.com/assets/14185797/25590600/cfad0040-2e76-11e7-942e-d7f7539ebe77.jpg)

**Comment by smok-e** [comment]
looks cool :-)

I use GIMP too, since many years
and know dafont.com
just would be interesting how you compiose the pictures.
my avatar is done in GIMP ;-)
was from a foto I found somewhere on the net
but heavy edited and layered and ...  ;-)

**Comment by ETPNV13** [comment]
I either create my own(I usually will use "colour paint" on linux to make a custom work of art)  or start with a digital copy of one I like and then resize to fit(select all and then resize image) my general purpose. If I want to do a certain color scheme I just "colorize" from the color menu and adjust the sliders until I am happy with the color and then just add text to my liking...pretty standard stuff, I like stuff with heavy black backgrounds because I find them easier to add more stuff to (or just darken the image to make any copy and pasted parts blend easier)Here's some Star Wars pics
![star wars iwo jima blue](https://cloud.githubusercontent.com/assets/14185797/25597255/5bdc19b8-2e93-11e7-9ec7-cdaf93a2ae63.jpg)
![star wars iwo jima](https://cloud.githubusercontent.com/assets/14185797/25597266/670b17da-2e93-11e7-816f-c6731644c0ec.jpg)

 I did for my desktop I built....
![star wars iwo jima blue2](https://cloud.githubusercontent.com/assets/14185797/25597245/4d5ec610-2e93-11e7-8d60-f044908b72ff.jpg)

**Comment by ETPNV13** [comment]
Here's one from my old dual boot linux laptop from a few years back...
![newwindowsbackground](https://cloud.githubusercontent.com/assets/14185797/25597488/8541c43c-2e94-11e7-9462-2964d45dfcff.jpg)

**Comment by smok-e** [comment]
here is a desktop I did inspired by your work
![1920x1080_fox_1](https://cloud.githubusercontent.com/assets/25061474/25638435/b5528bbc-2f88-11e7-9bd0-371747902a39.jpg)
I used some pictures by beksinski and edited and layered them in GIMP

**Comment by ETPNV13** [comment]
I like it!!!
