### ISSUE TITLE
iStick Pico 75w Clock gaining time

### ISSUE THREAD

**Issue by wackydude1234** [maelstrom2001/ArcticFox#30]
After setting the clock on the iStick pico after using it throughout the day the clock can gain anything up to an hour of time on the clock compared to the actual time of day, ArticFox 170103

**Comment by Gremdude** [comment]
Turning on the Light sleep will fix it. I had the same issue with my Cuboid and now it is dead on

**Comment by maelstrom2001** [comment]
Set Expert options:
X32 - Off
LSL - On
Power consumption in standby will increased slightly but the clock will be very accurate.
