### ISSUE TITLE
Charging pico

### ISSUE THREAD

**Issue by Manych23** [maelstrom2001/ArcticFox#303]
You've closed my previous issue, so I've started a new one.
The thing is, that on your firmware, when charging from 5V/1A, stops charging at 3.8-3.9 volts. And I should connect it to 0.5A charger to continue. There isn't such problem in stock.

**Comment by TBXin** [comment]
Oh boy...

> Charging on single cell boxes can not be controlled by firmware. Probably, Pico can not charge battery up to 4,18..4,20 volts (my Pico stops charging at about 4,16 volts), but on stock firmware 100% is equal to 4,10 volts (the same for GEN battery profile), so you never faced this issue on genuine Eleaf firmware.
