### ISSUE TITLE
Auto Off Feature?

### ISSUE THREAD

**Issue by Extermicide** [maelstrom2001/ArcticFox#306]
New to ArcticFox, and LOVING IT!

 Was looking thru the settings, and was wondering if (maybe i'm missing it), there's a way to have our device/mod auto-turnoff after a set time (lets say 3 mins) - to both conserve battery and as a safety precaution if unit is placed it in pocket or vape-bag. Kinda makes sense to me that if the unit is not gonna be used - to turn it off, and unfortunately being the human creature's we are, sometimes we forget.

Cheers, and Thank-U for all the hard work.

**Comment by adzam016** [comment]
+1 for this

**Comment by hawkeyexp** [comment]
Would be great  +1

**Comment by maelstrom2001** [comment]
Well, how about option in addition to standard deep sleep?
Now our boxes goes in deep sleep after 3 minutes of inactivity. We can easily add option to lock / power off device before it goes to sleep. In this way, if you're choosing some option, for example, "Lock on Sleep", box will be not wake up on single keypress from deep sleep, you'll have to power on it by 5 clicks. Is it suitable?

**Comment by hawkeyexp** [comment]
Sounds like a good option

**Comment by Tomozaki123** [comment]
me to +1

**Comment by maelstrom2001** [comment]
Released.
