### ISSUE TITLE
Do you love Arctic Fox?

### ISSUE THREAD

**Issue by adzam016** [maelstrom2001/ArcticFox#307]
Hi  Arctic Fox users!

First of all, I do not work for, endorse or even know the developers.

I just wanted to share my appreciation for these guys amazing firmware!

These guys have significantly improved our vape lives, and I am sure almost all of you will agree.

We keep requesting features and finding problems but I bet 80% or more of us will never consider donating to them!

I get paid on the 25th of this month and I will be giving a healthy donation to them.

If you like ArcticFox, give these guys a bit of credit for their time. Go on their official website and chuck them some money using the link.

By donating, we will be funding (and encouraging) these guys to continue to develop the firmware as well as add new devices etc.

Show the Arctic Fox team some love

Thumbs up if you donated, share the love!

**Comment by Niko1983** [comment]
I love it! I've no job, but I'm in for giving them a beer from me! They bring new life for my Wismec RX200S and I've bought the Joyetech VTCDual cause it's a supported one. If my contribution can help them, why not? :D

**Comment by mumpen** [comment]
I love ArcticFox and I'll donate $10000 if Predator support comes out today :P

**Comment by TBXin** [comment]
@mumpen I do not believe you 👿

**Comment by Niko1983** [comment]
I'll prefer to spend a couple of bucks on VTC Dual :D

**Comment by TimB87** [comment]
Can't donate much since I'm a broke ass student but I just did my part. 
Thanks for the great work guys! Eleaf/Joyetech/Wismec should donate generously since ArcticFox was my buying argument for the RX2/3 and Predator recently and I think this will apply to a lot of people!

**Comment by nifelvind** [comment]
Love u guys!
