### ISSUE TITLE
Is the eVic Primo 2.0 supported?

### ISSUE THREAD

**Issue by Justin-L-Franks** [maelstrom2001/ArcticFox#308]
I see in the [changelog](https://github.com/maelstrom2001/ArcticFox/wiki/Changelog) that support for the eVic Primo has been added. Does this include the eVic Primo 2.0 or only the original?

**Comment by nifelvind** [comment]
The upcoming release will support eVic Primo 2.0. The actual version does not support the 2.0 yet. So be patient ;)

**Comment by Justin-L-Franks** [comment]
Awesome. I'm in the market for a new dual-18650 mod that fits 24 mm and 25 mm atomizers without overhang, in order to replace my heavily-used and beat-up Cuboid, and I have come to rely on the features provided by the ArcticFox or myevic firmwares (especially the percentage-based power curves), and the eVic Primo 2.0 seems to be the best choice.

**Comment by acevalsl** [comment]
sorry, and evic primo mini??

**Comment by nifelvind** [comment]
As stated in the preliminary release notes, eVic Primo Mini will also be supported in the next release.

**Comment by maelstrom2001** [comment]
Released.

**Comment by Justin-L-Franks** [comment]
Awesome! Thanks so much. My new eVic Primo 2.0 will be delivered tomorrow or Thursday, and the first thing I am going to do is install ArcticFox.
