### ISSUE TITLE
Just 

### ISSUE THREAD

**Issue by espezetka** [maelstrom2001/ArcticFox#326]
Guys... 

I just wanted to say THANK YOU FOR ARCTICFOX! 
I am using AF every day since i know it and i have to say IT IS GREAT! 

So again : THANK YOU! :) 

Sorry for new thread...

**Comment by espezetka** [comment]
![tumblr_nmcd2zqzog1rf1jvro1_1280](https://cloud.githubusercontent.com/assets/26419510/25824012/217004a0-343e-11e7-8c83-8da19fb6dc00.jpg)

**Comment by arcticfoxer** [comment]
The new version is excellent. Especially foxy. There is no doubt that you will improve this practice even further. Thanks

**Comment by TBXin** [comment]
We are doing our best to create a good firmware ^^

**Comment by hawkeyexp** [comment]
Fantastic job guys !!!!

**Comment by nightshark** [comment]
Keep up the great work!
