### ISSUE TITLE
Disable AF logo on PowerOn and PowerOff animation

### ISSUE THREAD

**Issue by ReMicroN** [maelstrom2001/ArcticFox#327]
Hello! Can you add option in menu to disable AF logo on PowerOn and PowerOff animation. Thank You!

**Comment by TBXin** [comment]
Hello,

You do not like animation or something like that?
I am just want to understand for what reason you want to disable they.

**Comment by ReMicroN** [comment]
No. Animation is good. =) But I'm used to working screen immediately after "power on clicks" as on factory firmwares. So it will be good to make this option.

**Comment by dannysmobiles** [comment]
can i say this is good as it is if want it like the factory firmware then use factory firmware

**Comment by TBXin** [comment]
> So it will be good to make this option
You can just press Fire button once to skip welcome logo.

**Comment by Extermicide** [comment]
No disrespect "RemicroN" (as I fully understand where your coming from with the request), but let's look at it from/with the NFE Team's eyes and viewpoint.

They worked very hard on this software, and give it to us for free.  This software is "ART", and like any artist, they would like to "sign" their hard work.   Being that's the only thing they seem to ask, it's not unreasonable to allow them to "sign" their work.

Cheer's NFE TEAM - and Thank You!
