### ISSUE TITLE
Update Failed

### ISSUE THREAD

**Issue by drakjeee** [maelstrom2001/ArcticFox#33]
Device Name: Wismec Reuleaux RX 2/3
Firmware Version: 1.00
Hardware Version: 1.00
Boot mode: APROM

Firmware: af_170103.bin

Failuremessage: Opened firmware file is not suitable for the connected device.

**Comment by drakjeee** [comment]
Used old Version of NFE Toolbox

**Comment by TBXin** [comment]
Good that you solved the problem yourself ^^
