### ISSUE TITLE
Opened firmware is not suitable for the connected device

### ISSUE THREAD

**Issue by Gristrosia** [maelstrom2001/ArcticFox#330]
Hi,

I'm getting this message (_Opened firmware is not suitable for the connected device_) when I try to update my VTwo mini with the latest firmware and NF Toolbox 2.0. 

I found two older bug report with similar issue, I reverted to the stock firmware, I can update to previous firmware but still cannot upgrade to the new af_170508.bin firmware. 

Any idea? Is it "safe" to force the firmware update using the CTRL+ALT combo?

Thanks.

**Comment by maelstrom2001** [comment]
Hello! Re-download binaries, maybe something goes wrong. On my side:

**Comment by Gristrosia** [comment]
I tried to re-download the binaries, same issue. 
![capture](https://cloud.githubusercontent.com/assets/25066224/25827023/863ffc40-3449-11e7-87db-5977c5e5a8ca.JPG)

I'll try tomorrow on another OS like Windows 7.

**Comment by Gristrosia** [comment]
SAme issue with my Primo mini :(

![capture](https://cloud.githubusercontent.com/assets/25066224/25827196/3dbbdc68-344a-11e7-9f84-3327d2f5fa9d.JPG)

**Comment by nifelvind** [comment]
Maybe try another usb port

**Comment by TBXin** [comment]
@Gristrosia try to redownload firmware file via another browser. Seems your browser or proxy corrupted file during download process.

**Comment by Gristrosia** [comment]
Not sure if it's on my side. I tried all the firmwares, and I can update up to the  af_170331 without any issues. I tried to downloaded the file several times, AV off different browser. I downloaded NF Toolbox that apparently bumped version overnight (7.07 -- I had 7.02), still getting the same pop-up. 

I tried to force flash the firmware, getting a black screen on my evic VTwo mini.

Name:	af_170508.bin
Date:	5/9/2017
Size:	112 KB (114,688 bytes)
--------
SHA-1:	802bf0357899720f2daf9ddb2850f94cb06991e7
MD5:	593e4ca7152ea60e5764cef46d796634

**Comment by Extermicide** [comment]
Had same problem... Realized I was trying to flash the new binary with the old version of "NToolBox".

Downloaded the new version, all went well.

**Comment by TBXin** [comment]
> Not sure if it's on my side. 

I'm 100% sure, because many people have already written about the successful installation.

> I can update up to the af_170331 without any issues. 

Because you are running old NToolbox version. Close all instances and then start new one from 7.0.7 folder.
Your welcome screen should look like this:

![](http://i.imgur.com/fuxI9tl.png)

> re-flashed my original Wismec binary using their software.

This is not necessary operation.

>  Downloaded the new "NToolBox", and flashed the new ArcticFox binary.

Yep, this one helps ^^

**Comment by Gristrosia** [comment]
I'm using, and I used, the latest toolbox available (version 2.0 build 7.07 at the moment of writing) to flash the firmware - even the older. The one with the interface that look like this:
https://camo.githubusercontent.com/e8f75ec81e472aaad0912206d818f09906e52885/687474703a2f2f692e696d6775722e636f6d2f6675784939746c2e706e67

Still getting 
![capture](https://cloud.githubusercontent.com/assets/25066224/25844733/bfdf955c-34ab-11e7-9d0a-b0a02007e82d.JPG)

**Comment by GnFlala** [comment]
had exactly the same problem and all i did was to close Ntoolbox. Then i opened NFirmwareEditor (not ntoolbox) directly from the folder, pressed on Tools->Firmware Updater->From file.
That way i managed to update to latest firmware. 

From within Ntoolbox Firmware update i was getting Not suitable for this device. 

I don't know if that helps, but its all i got.

**Comment by ReMicroN** [comment]
Maybe another HW version?

**Comment by TBXin** [comment]
@Gristrosia redownload NToolbox archive and extract it to the newly created folder, eg: C:\NFE\
Also you can try to start NToolbox.exe with option "Run as administrator".

**Comment by khamien** [comment]
Same here running windows 7. Tried multiple USB cables on different USB ports. Tried administrator, NFirmware editor. Same error message on RX200, RX200S, PICO and PREDATOR. The 3 first ones accept 170201, but no way to push 170508.

**Comment by Gristrosia** [comment]
Thanks GnFlala, I managed to flash my evic vtwo with the latest firmware.

Starting NFirmwareEditor.exe crashed on start with the error log complaining about the implantation of FIPS. I disabled FIPS in Windows Local Security Policy, tried to flash, and it worked. 

If anyone has the same issue trying to "af_170508.bin" upgrade to check if "_Use FIPS 140 compliant cryptographic algorithms, including encryption, hashing and signing algorithms_" is disabled. "Disabled" is the default settings, but some Wifi drivers enable the setting when you install them. Or if you followed a STIG to secure your machine ...and forgot about this problematic setting like me;;

**Comment by TBXin** [comment]
@Gristrosia thanks for the explanation!

A little excerpt from the article:
“FIPS mode” doesn’t make Windows more secure. It just blocks access to newer cryptography schemes that haven’t been FIPS-validated. That means it won’t be able to **use new encryption schemes**, or faster ways of using the same encryption schemes. In other words, it makes your computer slower, less functional, and arguably less secure.

That's why NToolbox can't decrypt firmware and find related PID.

Thanks again.

**Comment by khamien** [comment]
![af](https://cloud.githubusercontent.com/assets/28575790/25874179/b90fa396-3511-11e7-9c3f-c85424e74e1f.JPG)
FIPS already disabled here. Will try on another computer when I have a chance.

**Comment by Gristrosia** [comment]
@TBXin yes, I usually disable it on my home desktop, but keep it enabled on my laptop where FIPS being enabled is more critical/important.  I have the same GPO backed up for both machine, and I forgot about it/to turn it off on the desktop when I upgraded to Windows 10 rs2 :/ 


If you want more detail about why or _not_ enable it and 
https://blogs.technet.microsoft.com/secguide/2014/04/07/why-were-not-recommending-fips-mode-anymore/

**Comment by khamien** [comment]
Gave up trying on my own computer, no idea why it does not work while precedent releases did.
but I could manage to flash my predator today from a computer at work -really appreciated NFtoolbox beeing a no-install folder- also running windows7. 
You guys rock, after using "myevic" I loved ArcticFox on my other boxes, and really expected it on wismec predator, relieved. Thanks so much for bringing that to us, congrats and maximum support!

**Comment by forkoz** [comment]
Had this issue but updating toolbox allowed the upload.
