### ISSUE TITLE
Wattage over 100 bug Predator228

### ISSUE THREAD

**Issue by xandersk** [maelstrom2001/ArcticFox#331]
If the power is 100+ W the first digit disappears when firing. Eg: 100 would be 00

Happens on the new Foxy Interface on the Predator228

![ezgif-1-18a9fd408a](https://cloud.githubusercontent.com/assets/22568713/25826803/26a4332c-3440-11e7-9284-50ce6e3a297e.gif)

Edit: happens only at 100W and when using 1 Watt mode

**Comment by xandersk** [comment]
For now i'll just use 101W 😄  Great update, definitely worth the wait!

**Comment by maelstrom2001** [comment]
Yep, thank you, bug was found, wrong power value rounding. Try this [nightly](http://nfeteam.org/nightly/af_170509.bin) please.

**Comment by xandersk** [comment]
Fixed it, thanks for your work @maelstrom2001  👍
