### ISSUE TITLE
Eleaf Istick  Pico Double TC view

### ISSUE THREAD

**Issue by andrewchemerys** [maelstrom2001/ArcticFox#332]
Eleaf Istick  Pico Double TC view
![sketch](https://cloud.githubusercontent.com/assets/28547227/25827179/89e03316-3452-11e7-889b-03d249876be4.png)

**Comment by TBXin** [comment]
@andrewchemerys already fixed.
https://ci.appveyor.com/project/TBXin/nfirmwareeditor/build/7.0.7/artifacts
