### ISSUE TITLE
new skin

### ISSUE THREAD

**Issue by Bergo82** [maelstrom2001/ArcticFox#333]
Hello Dev's

i installed the new relase and i'm wondering about the three dots at the left upper corners
![2017 05 09 01 45 09](https://cloud.githubusercontent.com/assets/28549421/25830207/9d7ca158-345b-11e7-94b8-c194a2988ec2.png)

which information will show there?

regards Bergo

**Comment by TBXin** [comment]
Hello,

This is Preheat, Stealth Mode and LSL indicators.
If one of this is enabled dot will be changed to the related icon. 

By default dot means nothing :) just a placeholder.

**Comment by Bergo82** [comment]
thanks
