### ISSUE TITLE
Imposible upload logo

### ISSUE THREAD

**Issue by acevalsl** [maelstrom2001/ArcticFox#338]
always say this error.
after update work fine.

vtwo mini and primo mini

<img width="1253" alt="captura de pantalla 2017-05-09 a las 13 00 58" src="https://cloud.githubusercontent.com/assets/22813078/25847766/bf3c5c00-34b7-11e7-86ac-8e3812a1579c.png">

**Comment by Bergo82** [comment]
i use the origin update tool to install the logo it do it without any issues

**Comment by acevalsl** [comment]
Nice, with original update go fine. txs
