### ISSUE TITLE
QuickCharge 2.0

### ISSUE THREAD

**Issue by Bergo82** [maelstrom2001/ArcticFox#339]
is it possible to get an reverse charge output of QuickCarge1.0 5V and 2Amps or better Quickcharge2.0 5V/2A and 9V/2A?

thanks a lot for the past and future Work

**Comment by TBXin** [comment]
Hello,

QuickCharge is not just an increased voltage, it is primarily an interaction protocol, which determines the supported mode.

Device can't send or read any data by 510 connector. And this why implementation of the QuickCharge is not possible.

**Comment by Bergo82** [comment]
then is it possibe to get 2A with the 5V like a dump powerbank?

**Comment by TBXin** [comment]
@Bergo82 Power Bank mode Can provide up to 2.1A for your devices.

**Comment by Bergo82** [comment]
ok it is allready implementet?

**Comment by TBXin** [comment]
@Bergo82 yes.

**Comment by Bergo82** [comment]
perfect
