### ISSUE TITLE
Link over Wiki refers to outdated versions.........

### ISSUE THREAD

**Issue by IngoPOW** [maelstrom2001/ArcticFox#342]
Link over Wiki refers to outdated versions.........

Took me some time to find the newest version over the releases button.
Even the Link in the actually Toolbox refers to the old versions.

regards,
Ingo

**Comment by TBXin** [comment]
Changelog on the wiki is only for nightly builds.

![](http://i.imgur.com/pcSAEyg.png)

Even a note about NToolbox says it:
> Builds are compatible with nightly NToolbox, which can be downloaded here.
