### ISSUE TITLE
Egrip 2 light turn off the led or chage color

### ISSUE THREAD

**Issue by komaramnt** [maelstrom2001/ArcticFox#348]
Hi,
maybe it is not a problem but I can't find the setting to turn off the led in the tank... or there isn't that option?
Thanks in advance!

All of you are doing great work!!!!!

**Comment by TBXin** [comment]
Hello,

At this point there are no such option. LED should lights every time you press Fire button.

**Comment by komaramnt** [comment]
Thanks for your quick response! The only way will be to edit the source ?

**Comment by maelstrom2001** [comment]
If you're concerned about battery drain turn Stealth Mode on.
