### ISSUE TITLE
Possible to revert back to original firmware?

### ISSUE THREAD

**Issue by mcrevo96** [maelstrom2001/ArcticFox#353]
Just wanted to check if it's possible to revert back to the original firmware, if I just want to test this and don't like it for some reason? I have the Evic VTC Mini.

**Comment by TheSpiritof69** [comment]
Yes it is. Just flash the original firmware back.

**Comment by mcrevo96** [comment]
Ok, thanks for the quick reply. :) I'll give this a try then, seems fancy.
