### ISSUE TITLE
ohm value decrease when firing?

### ISSUE THREAD

**Issue by edward81** [maelstrom2001/ArcticFox#354]
Evic primo with dual coil ss316l.
I just updated the new firmware (can't confirm with the old) 170510. And i get this strange behaviour. The resistance decrease when i fire. After firing the resistance go up again.
![screenshot_20170510_222208 jpg](https://cloud.githubusercontent.com/assets/569597/25919638/8a6c0020-35cf-11e7-8a96-cf0a72f3a878.png)

**Comment by maelstrom2001** [comment]
It is normal behavior. In standby mode all boxes shows increased Live Resistance. Some higher, some lower, but all of them.

**Comment by cpulley** [comment]
Is it possible to add an offset for this, maybe an expert setting?  I'm not 100% sure if it's the same issue, but my Cuboid is showing a coil at 3.13 ohms at rest, when it's actually a 1.05 ohm coil. Sadly, this makes most of the info on the screen useless, and limits me to 25.9W (as it thinks it'll be firing at 9V)

![incorrect ohms](https://cloud.githubusercontent.com/assets/3003520/25928212/9f2fc5f0-35c0-11e7-9801-1b9d6d9b74a8.png)

**Comment by Justin-L-Franks** [comment]
@cpulley I had a similar issue recently on my Cuboid running the myevic firmware -- a 1.2 ohm coil was reading as 2.1 ohms cold, but when firing read correctly. Turns out the 510 connector was just a bit dirty. After cleaning it with a bit of alcohol and cotton, the problem disappeared.

**Comment by edward81** [comment]
How i can lock cold resistance if the mod show me the wrong value?

**Comment by TBXin** [comment]
> How i can lock cold resistance if the mod show me the wrong value?

You can lock any resistance and then correct value in the Profile Menu of the device or in the NToobox.
