### ISSUE TITLE
powerbank mode

### ISSUE THREAD

**Issue by khamien** [maelstrom2001/ArcticFox#360]
Great feature, but how can i disable auto sleep in this mode?
Box shuts off and stops charging device. Hitting fire makes it wake up and charge again.
This does not happen on wismec predator that have native reverse charging feature, but with rx200, 200s and pico75. Using eleaf avatar.

**Comment by maelstrom2001** [comment]
In Power Bank mode box going to sleep in approx. 10 sec if output current is not exceed 50 mA. May be current drain was too low?

**Comment by khamien** [comment]
Nope, a bit lower than 1A.

**Comment by maelstrom2001** [comment]
How long did you use the Power Bank mode? Right now charging e-reader from Pico, it lasts continuously for 20 minutes with no interrupts (about 0,5 amps output). All standard protections are used, also charging stops on low battery and overheat.
