### ISSUE TITLE
Battery cut out at 3.5V

### ISSUE THREAD

**Issue by yoshy262** [maelstrom2001/ArcticFox#361]
Please, can you set the batery cutout at 3.15 V or 3.25 V?

The Wismec Fw cutout the batery at 3.25V, Arctic cutout at 3.5V.
Is not quite optimal for a batery to be recharged at 3.5V because is not drained.
I know, is a safety issue but 3.15 or 3.25 is very, very safe to drain a battery till at 2.9V or 3V.

**Comment by TBXin** [comment]
Hello,

This was a little bug in the GEN discharge profile.
You can install latest available release https://github.com/maelstrom2001/ArcticFox/releases/tag/170510
And problem should gone.

Also, you can create custom discharge curve with custom cut-off value and custom points.

**Comment by yoshy262** [comment]
Thank you very much for a very fast answer.
I already put the new Fw on the Predator.
