### ISSUE TITLE
Lose profile when sleep

### ISSUE THREAD

**Issue by dedone** [maelstrom2001/ArcticFox#364]
Hi,
first of all THANKS!!!!!!!!!

After last update (170510), with Evic Mini, it lost the profile when go in sleep.

I genarelly use ni200 with a kayfun mini v3 and with this new update sometimes it turn on the watt profile after sleep.
It never happen with previous update.

**Comment by maelstrom2001** [comment]
Switch Smart mode to Lazy, it should eliminate profile switching on wake up.

**Comment by dedone** [comment]
Prefect, done!!!!

**Comment by ETPNV13** [comment]
For me it switches on lazy when I enter the main menu for some reason, so I just swithed it off completely and problem fixed lol
