### ISSUE TITLE
Unable to download device settings

### ISSUE THREAD

**Issue by TiborBarath** [maelstrom2001/ArcticFox#365]
Hi i have problem with my Eleaf iStick Power80.
I try to use ArcticFox and i get this issue.
Anybody can help me what am i doing wrong?

I try iStick Power firmware 1.0.1 - 1.0.2 - 1.0.3
and i try ArcticFox 6.0 - 6.5.0 - 7.0.7
Same problem all this variations.

And i try this in pc and laptop (with original cable)

![clipboard01](https://cloud.githubusercontent.com/assets/28656279/26007538/2d863bf0-3741-11e7-80d0-5bf9419216a0.jpg)

**Comment by maelstrom2001** [comment]
Did you flash the latest firmware? Post screenshot of Firmware Updater with connected box.

**Comment by TiborBarath** [comment]
![clipboard01](https://cloud.githubusercontent.com/assets/28656279/26007889/b3beb85e-3742-11e7-94fb-1153ca6b1484.jpg)

**Comment by maelstrom2001** [comment]
Firmware Version is stock. It is NOT ArcticFox.

**Comment by TiborBarath** [comment]
Ah i need download ArcticFox firmware and then try? :)

**Comment by TBXin** [comment]
Yes

**Comment by maelstrom2001** [comment]
You'll not beleive...

**Comment by TiborBarath** [comment]
Its working! Thank you guys!
