### ISSUE TITLE
Battery v 

### ISSUE THREAD

**Issue by dannysmobiles** [maelstrom2001/ArcticFox#368]
Hi how low does battery's voltage goes dw to thanks

**Comment by dannysmobiles** [comment]
Is ok found out is 3.20v

**Comment by ETPNV13** [comment]
You can set it to 2.75 as well on the custom curves

**Comment by dannysmobiles** [comment]
I'm happy with the 3.20 well when it gets to 3.20v it comes up with battery's weak but can still vape and battery's say 4%

**Comment by GnFlala** [comment]
while you fire you get a voltage drop. That is where cut off works. The curve is nothing more than precentage on the screen and has nothing to do with actual battery. just visual reading for our eyes.
