### ISSUE TITLE
Wiki Request

### ISSUE THREAD

**Issue by Dil3mm4** [maelstrom2001/ArcticFox#374]
Hello there @TBXin @maelstrom2001 .
I've just translated and restyled a bit the wiki. 
Take a look on my forked [repo wiki](https://github.com/Dil3mm4/ArcticFox/wiki) to see how it looks like!
Can you add me as a collaborator so I can set it up if you like it?
Thank you for your attention, as always.
Have a nice day.

**Comment by TBXin** [comment]
Hello,

Thanks for your suggestion, but this wiki is deprecated. In our plans to create separate category on the forum which will be related to guides and other similar things.
