### ISSUE TITLE
[Possible bug?] Spikes in live battery voltage reading in device monitor.

### ISSUE THREAD

**Issue by sandbagjohnny** [maelstrom2001/ArcticFox#38]
Hi, 

Great job on this firmware, it is much nicer than the stock firmware on many levels :)

I'm reporting a possible problem with power over USB. I've got two eLeaf Pico's, bought 4 months apart, the first one in June 2016 and the other in November 2016. In device monitor, the voltage reading spikes from whatever the battery voltage is, to 5.12v, whenever the device is fired. I've also posted this bug at TBXIN's repo

[Pico A is set to power mode. Voltage spikes are circled in red.](http://imgur.com/T1pUTao)

[Pico B is set to TC PI mode. Voltage spikes are circled in red.](http://imgur.com/81tQnij)

**Comment by TBXin** [comment]
This spikes are result of the bad quality ADC and him noise.
Device Monitor just visualize data, that device send.

P.S.
Both repo are our, so you don't need to duplicate issues.

**Comment by sandbagjohnny** [comment]
Thanks.

I moved my charging station to another PC this morning as a test. (Sometimes the USB ports lose connection on this PC I'm typing on) I've noticed these spikes in the battery voltage signal went away. Poor signal/connectivity from USB port itself can cause this too? Is this correct?

**Comment by TBXin** [comment]
Nope, this is incorrect.

**Comment by sandbagjohnny** [comment]
hm, ok. Thank you.. Maybe I just got giddy that I didn't see anything weird on the other PC yet.. I still can't seem to reproduce it on this other different PC though so it's all good.

**Comment by sandbagjohnny** [comment]
Would it be possible to write a noise filter into either the fw code, or the toolbox? Thanks!
