### ISSUE TITLE
screens not centered

### ISSUE THREAD

**Issue by cdyseplc** [maelstrom2001/ArcticFox#382]
all the screens for all 3 themes are not centered, is there a way that i can center them via the toolbox or something?

**Comment by m600x** [comment]
they are all centered, no.

**Comment by TBXin** [comment]
What do you mean?
You can take a screenshot and count the pixels.

**Comment by cdyseplc** [comment]
will do that and get back soon

**Comment by cdyseplc** [comment]
![2017 05 20 18 03 55](https://cloud.githubusercontent.com/assets/28722232/26274920/f4180478-3d87-11e7-9a88-df7341ea8988.png)
![20170520_180535](https://cloud.githubusercontent.com/assets/28722232/26274919/f416bfe6-3d87-11e7-98b3-09de4e058e05.jpg)
![20170520_180556](https://cloud.githubusercontent.com/assets/28722232/26274921/f418bbac-3d87-11e7-829b-ea40ddc2bee7.jpg)
![20170520_180844](https://cloud.githubusercontent.com/assets/28722232/26274922/f419bc3c-3d87-11e7-8ccd-3c6936d511b6.jpg)
![20170520_180928](https://cloud.githubusercontent.com/assets/28722232/26274923/f41f61a0-3d87-11e7-9a13-945a7fdabd2f.jpg)


here are the screens!

**Comment by joeblowma** [comment]
You can blame wismec for that, where they mounted the screen there is no guide to hold the screen centered/straight (a few people have gotten screens at an angle), it's just stuck there with some double sided tape and the ribbon soldered down to the PCB.

Mine is set a little too high up but relatively centered, and really far back from the glass - it might have worked out perfect if they had used thicker tape.

**Comment by cdyseplc** [comment]
its not actually if you see the first screen, it is off by maybe one or two pixels

**Comment by cdyseplc** [comment]
![20170520_195205](https://cloud.githubusercontent.com/assets/28722232/26275545/fd0bdf42-3d95-11e7-927e-5653fd28a237.jpg)

**Comment by TBXin** [comment]
Actually you can't draw pixel perfect circle with a width/height of a multiple of 2. Thats why you can see 1 pixel gap from the left.

**Comment by cdyseplc** [comment]
okok its ok then =)
