### ISSUE TITLE
Battery indication in Power Bank mode

### ISSUE THREAD

**Issue by ilyxa** [maelstrom2001/ArcticFox#385]
Checked on Pico 75.
Battery indication "stuck" in fully charged state all time while power bank was on (load current was about 0.3A if this is important, Avatar RC connector is in use). 

Problem: The battery indicator did not change until the box was completely turned off. Looks like this is bug in UI?

**Comment by maelstrom2001** [comment]
Thanks for report, yep, possible bug. Will take a look.

**Comment by ilyxa** [comment]
Also checked on Cuboid 200 - same problem.

**Comment by maelstrom2001** [comment]
Please test attached build. Note that under load (while Power Bank is on) battery indicator will display battery level lower than in standby. It is normal, 'cause battery voltages will drop a little under load.

[af_170517.zip](https://github.com/maelstrom2001/ArcticFox/files/1006067/af_170517.zip)

**Comment by ilyxa** [comment]
Work as expected, checked on Pico 75.
![dsc_0028](https://cloud.githubusercontent.com/assets/153595/26147463/4f78d100-3afc-11e7-9933-a0107a1e7779.JPG)
![dsc_0029](https://cloud.githubusercontent.com/assets/153595/26147464/4f93d6bc-3afc-11e7-8664-f7f3b1ef8e04.JPG)

Thank you!
