### ISSUE TITLE
Battery voltage in displayed inverted colors on charge screen

### ISSUE THREAD

**Issue by malinges** [maelstrom2001/ArcticFox#387]
Hi,

I've been charging my Predator with USB, and noticed that sometimes, one of the batteries' voltage is displayed in inverted colors:
![_20170516_164726_small](https://cloud.githubusercontent.com/assets/1636924/26128439/75262f4e-3a5a-11e7-970d-2b569d391058.jpg)
What does that mean?
Is this somehow related to balanced charging?

BTW, great work guys! ArcticFox is getting better and better ;-)

**Comment by TBXin** [comment]
Hi,

This is how "balancing" works. Inverted battery means that this battery is waiting until other battery voltage is not become same.

For future read this please: https://github.com/maelstrom2001/ArcticFox/issues/386

**Comment by malinges** [comment]
Ok, that's what I thought, but I wasn't sure.
I'll also be keeping an eye on the forum...
Thanks!
