### ISSUE TITLE
Question about new batterie profiles

### ISSUE THREAD

**Issue by smok-e** [maelstrom2001/ArcticFox#39]
I would like to add profiles for some different batteries.
But now I can only use 1 custom profile. 
It would be great if there was an option to save the custom profile (external on my PC)
like the wire profiles. And load a custom profile from a csv file.
Would it be possible to implement this?

**Comment by TBXin** [comment]
If i understand you correctly - you want import/export function in the MFE Toolbox - ArcticFox Discharge Profile editor?

**Comment by smok-e** [comment]
yes, you understand it correctly. Would that be possible?
This way we could add curves for more batteries.

**Comment by Joergl100** [comment]
What discharge current is according to the curves? Maybe...we could build individual ones...with an adequate charger with diagnostics/monitoring as the MC3000?

**Comment by TBXin** [comment]
Primary values in the discharge curve is a voltage, not current.

**Comment by Joergl100** [comment]
Ok, thanks!

**Comment by TBXin** [comment]
Discharge Curve Export/Import will be included in the next release.
![](http://i.imgur.com/AUIF1Dt.png)

**Comment by smok-e** [comment]
thanks :-)

**Comment by Joergl100** [comment]
Excactly the same as unedited in "Custom"...
