### ISSUE TITLE
How to restore the original firmware?

### ISSUE THREAD

**Issue by vojaly** [maelstrom2001/ArcticFox#398]
i am vtc dual.
fw:Af_17510

Do not recognize devices with official upgrade procedures. Safe mode is the same.

**Comment by TBXin** [comment]
Upload OFW via NToolbox, after this you will able to use original updater as usual.

**Comment by vojaly** [comment]
My equipment is out of order and needs to be repaired. It needs to be restored to its original firmware.

thanks for help.
