### ISSUE TITLE
Battery voltage RX200

### ISSUE THREAD

**Issue by frogontherox** [maelstrom2001/ArcticFox#4]
The Battery Voltage on the RX200 HW Ver.1.00 is going Wrong. The batterie(s) are fully loaded @4,17V.

![2016 12 22 00 17 08](https://cloud.githubusercontent.com/assets/24706325/21409728/196771b8-c7dc-11e6-96ab-3bb6c98f0dca.png)

**Comment by TBXin** [comment]
Thanks for very fast report ^^
It seems different HW versions used different DAC's.
We are working to fix this issue on 1.00, 1.03 hardwares, 1.04 works fine.

**Comment by frogontherox** [comment]
Thank you for the answer. The Arctic fox is a great firmware!!!! I hope it will work on my "old" RX200.
I use this mod on my other divices (Evic Vtc, Cuboid, RX 2/3) and it works great! Thank you.

**Comment by TBXin** [comment]
It will! We just found what causing this strange behavior. Today we will create ArcticFox release with fix.

**Comment by frogontherox** [comment]
Wow! I will test it ;-) Thank you!

**Comment by maelstrom2001** [comment]
Please test the latest release: https://github.com/maelstrom2001/ArcticFox/releases/161222

**Comment by frogontherox** [comment]
Tested! Works great!

**Comment by maelstrom2001** [comment]
Thank you for response, nice to hear that bug was fixed :)
