### ISSUE TITLE
Eleaf Aster... gaining time.

### ISSUE THREAD

**Issue by febs** [maelstrom2001/ArcticFox#41]
This is likely similar if not identical to this one.

https://github.com/maelstrom2001/ArcticFox/issues/30

That has been closed so I unfortunately have to open a new one.
I did apply the changes recommended in that issue:

Set Expert options:
X32 - Off
LSL - On

But the clock still ran ahead of time. About one hour per day.

Thanks

**Comment by TBXin** [comment]
Bad for you :)
Aster does not have RTC module, so talking about accuracy like a joke^^

**Comment by febs** [comment]
May I suggest then to disable that for the aster? It makes no sense then.
Just considering.  Thanks for caring!

**Comment by TBXin** [comment]
Hide it for yourself.

**Comment by febs** [comment]
I did just gave a suggestion, I didn't pretend anything...
