### ISSUE TITLE
Eleaf Pico Dual support

### ISSUE THREAD

**Issue by febs** [maelstrom2001/ArcticFox#42]
I just bought it and realized that oh noes Arctic Fox doesn't run on it and oh my godz how much the stock firware suck compared to it.

Any chance?

Thanks!

**Comment by TBXin** [comment]
Already done, but not released yet.
You can try nightly build or wait for release.

**Comment by febs** [comment]
MARRY ME <3

**Comment by maelstrom2001** [comment]
Added early support of Pico Dual: nightly [af_170112.bin](https://dl.dropboxusercontent.com/u/43399149/VTC/arcticfox/nightly/af_170112.bin)
**Untested, may be very buggy, use at your own risk, no warranties at all!**
Use nightly [NToolbox](https://ci.appveyor.com/api/buildjobs/q43eu4e4eylvf107/artifacts/src%2FNFirmwareEditor-v6.4.17.zip) to install and configure.
