### ISSUE TITLE
[RFC] Remove restriction 0.05 for TC and 0.1 for VW, and use only 0.05

### ISSUE THREAD

**Issue by Nefelim4ag** [maelstrom2001/ArcticFox#43]
Device: RX2/3
TC and VW modes have different resistance limitation:
Resistance Range: 0.05-1.5ohm for TC modes
Resistance Range: 0.1-3.5ohm for VW mode

I don't know why this modes have a difference but i think this is only software limitations and it can be easy removed/merged i.e. to 0.05-3.5ohm

Example: I have a Griffin 25 with top airflow, i try intall dual clapton from SS316L, and i can't check coils in VW mode because resistance are too low (0.098).

Thanks.

**Comment by maelstrom2001** [comment]
Use higher resistance for your own safety.
