### ISSUE TITLE
RX 300 SUPPORT 

### ISSUE THREAD

**Issue by docdeath** [maelstrom2001/ArcticFox#48]
firmware loads  ok still not working as its only seeing one battery in BVO .menu all works fine so
far with 
af_170113.bin

**Comment by maelstrom2001** [comment]
Please try this build: [af_170114.bin](https://dl.dropboxusercontent.com/u/43399149/VTC/arcticfox/nightly/af_170114.bin)

**Comment by docdeath** [comment]
its working now , all as it should  only thing is in nfe tool box only shows 3 battery but apart from that all working sofar

**Comment by maelstrom2001** [comment]
Oops :) Thanks, I forgot about it. Please re-download binary.

**Comment by docdeath** [comment]
all working as it should do  very good job there

**Comment by maelstrom2001** [comment]
Thank you very much for testing and response, keep issue opened until full support will be implemented. Or some new bugs will appear :)

**Comment by OlafKroll** [comment]
not work on my RX 2/3 :-)

**Comment by maelstrom2001** [comment]
> not work on my RX 2/3

What it means? Can not install firmware, box not start, shows something wrong, or what?

**Comment by OlafKroll** [comment]
After install.
Can´t connect via Artifox Configuration.
means... use a newer Firmware

**Comment by TBXin** [comment]
For this AF build you need nightly Toolbox build

**Comment by docdeath** [comment]
JUST  one thing to ask there is there battery % some where or is not in there . for rx300

**Comment by OlafKroll** [comment]
oh sorry my fault

**Comment by maelstrom2001** [comment]
@docdeath it should be there selectable:
![](http://i.imgur.com/kEhaR1m.png)

**Comment by docdeath** [comment]
wops my fault not looking thanks

**Comment by docdeath** [comment]
i see you have posted 14a bin any changes for rx300

**Comment by maelstrom2001** [comment]
There is a little fix for RX300, maybe not necessary. If it possible, please test too.
14a in main contains bugfixes for Pico Dual.

**Comment by docdeath** [comment]
tested 14a  all working as should do  cant see any problems  been using  for 10hrs

**Comment by Ustes** [comment]
great work. Tried this on my rx300 with no issues.  Is there any way to show all 4 battery status?

**Comment by maelstrom2001** [comment]
@Ustes Thanks! You can see all battery status on Info Screen on 2nd page (+ and - changes page), or switch skin to Circle: Battery Volts line should display voltages consequentially from 1 to 4 while display on.

**Comment by Ustes** [comment]
@maelstrom2001 thanks for the info.  Why do you say seeing all 4 battery icons is useless?  I like the 4 cause it shows me if a battery is getting out of balance at a quick glance.  Just my 2 cents. Again, thanks.

**Comment by docdeath** [comment]
@Ustes  having RX300 myself  i tested the battery state  and the 4  icons where so out off balance  it was  like maelstrom said worth less and if they are out off balance the mod lets you know in stock firmware and so dose  this firmware so no need for 4 icons  just my 2 cents.

**Comment by Ustes** [comment]
@docdeath so what yall are saying is that those 4 icons are not right anyway? if that is the case going back to AF!

**Comment by docdeath** [comment]
ustes  in all fairness the icons are there to give you  rough est  off battery life if you want 100%  proof buy dna chip set Wismec don't say any where in info for this mod that battery icons are 100% spot on and never will do   if you feel your being hard done by then feel free to sent mod back  but my self i am keeping mine as i can always use bvo to see battery's

**Comment by Ustes** [comment]
@docdeath in all fairness I don't think you understood what I wrote.  I said if what you all are saying is that the 4 icons are never correct, I am going back to flash ArcticFox(AF).  I was agreeing.  Where did I say anything about I want 100% battery accuracy, or that I was being hard done (what ever the fuck that is)?  
Pump ya brakes sun!

**Comment by docdeath** [comment]
@Ustes if i have upset you then sorry and feeling hard done by is brit saying for not as you expected

**Comment by maelstrom2001** [comment]
@docdeath Hello! Can you confirm that BVO for 4th battery is not working? Thanks in advance!
#53

**Comment by docdeath** [comment]
@maelstrom2001  its not working tested

**Comment by maelstrom2001** [comment]
Thanks, do you changed BVO with NToolbox or on RX300 in Expert Menu? If you edit BVO in Expert Menu in mod, does it work?

**Comment by docdeath** [comment]
i have just tried both  and will not work in both

**Comment by docdeath** [comment]
@maelstrom2001  my bad retested in ntoolbox and it works but not working if you use in mod menu

**Comment by docdeath** [comment]
@maelstrom2001 that seams to have fixed that BVO  mod menu

**Comment by maelstrom2001** [comment]
Nope :) on mod's side did nothing with BVO in today's build. If ain't broke don't fix it :)
Today we should have functional balancer and... charging via USB. Maybe. It's done, but disabled.

**Comment by docdeath** [comment]
@maelstrom2001  ok that's strange as if i remove battery's and put new set in it works once then nothing using mods bvo menu

**Comment by docdeath** [comment]
@maelstrom2001  when mod is plugged in to usb and charging it do.s  not change screen or shut down to show charging  screen  ,it just stays on main screen and batt icon show its charging  but in really strange movement it go back and fourth then speed up and slow down so have turned off charging

**Comment by maelstrom2001** [comment]
@docdeath Thank you for response! It seems that charging constantly switches on and off by itself, and thats why mod never goes to sleep. Will upload some new test version soon.

**Comment by maelstrom2001** [comment]
[170117a](https://dl.dropboxusercontent.com/u/43399149/VTC/arcticfox/nightly/af_170117a.bin) uploaded, please test it.

**Comment by Obicom** [comment]
@maelstrom2001: Any proposal what I can check regarding no charging on my device?

**Comment by docdeath** [comment]
@maelstrom2001 the 117a is working but you can not turn off in mod menu or ntool also  it still not going to sleep it gets stuck  as in screen shot 
![2017 01 17 20 39 16](https://cloud.githubusercontent.com/assets/23120839/22039076/b582e9aa-dcf5-11e6-8ae4-3b849c7c6f21.png)

**Comment by maelstrom2001** [comment]
@Obicom As **docdeath** wrote above, charging routine in 170117 is still very buggy. Something ATM goes wrong, need time to investigate.

@docdeath thank you! Is behaviour of battery icon (charge progress) better than 170117 (without "a") or the same?

**Comment by docdeath** [comment]
charge progress is far better with 170117a than 117

**Comment by Obicom** [comment]
@maelstrom2001 : af170117a.bin installed and start charging with 670 mA on USB tester.

![170117a](https://cloud.githubusercontent.com/assets/25134482/22039422/80a7f0fe-dcff-11e6-84e9-e4719eb2730e.JPG)

**Comment by maelstrom2001** [comment]
@Obicom @docdeath thanks a lot, you're great testers, much appreciated!
And 2 more test, please:
- while box charging, switch Stealth Mode on. After dim timeout charging screens should disappear;
- disconnect USB, switch stealth off, switch box off by 5 clicks. Now plug USB in. Box should start charging.

**Comment by Obicom** [comment]
1.) works as expected
2.) works as expected

well done

**Comment by maelstrom2001** [comment]
@docdeath 
> can not turn off in mod menu or ntool also it still not going to sleep it gets stuck as in screen shot

Well, I think it is right and regular behavior. While mod is charging, it always shows screenshot like you provided. No matter in what state is it - on or off. If it goes to main screen from that on keypress and went back to charging screen after some time - all goes right :) Black screen on USB connect we can get in 2 cases:
- Stealth Mode is on
- batteries are fully charged, so box can go to deep sleep

In other cases charging screen will appear.

**Comment by docdeath** [comment]
same here all worked  as above to

**Comment by docdeath** [comment]
@maelstrom2001  so can you disable usb charge from mod menu and ntool box still because  i cant  in ntool i untick box  and upload and still charging  unplug usb replug in still charging  open mod menu with out usb plugged in  usb charge is off , but still charging  when i plug usb in

**Comment by maelstrom2001** [comment]
@docdeath Yes, this option will be implemented for sure. Need a little break for refactoring code, and then I'll ask you to test build with it. Maybe even tomorrow :) for now you can use previous builds with disabled charging in hard code.
In 170117a build indication of charging is working, but physically box should not take current from USB when "USB Charge" option is disabled.

**Comment by maelstrom2001** [comment]
[170118](https://dl.dropboxusercontent.com/u/43399149/VTC/arcticfox/nightly/af_170118.bin)
Refactored, please test. "USB Charge" option also should work.

**Comment by docdeath** [comment]
yes that works ok can turn  on and off in ntool and mod menu

**Comment by Obicom** [comment]
and with USB current tester it works fine ... charge off = 0mA, Charge on = 680 mA

**Comment by maelstrom2001** [comment]
Thanks a lot for responses! What you think, we have to implement stock Wismec charging algo up to 1,5 amps or staying on "old" 1,0 amp limit?

**Comment by Obicom** [comment]
With four batteries I would prefer the 1,5A current to get faster charging results.

**Comment by Obicom** [comment]
@maelstrom2001 : Is Avatar charging adapter support in focus?

**Comment by docdeath** [comment]
@Obicom  really? you charge in mod

**Comment by docdeath** [comment]
@maelstrom2001  to be safe i would stick to 1.amp

**Comment by Obicom** [comment]
@docdeath : Normally not but if I would do I would prefer 1.5A ;)

**Comment by maelstrom2001** [comment]
> Is Avatar charging adapter support in focus?

In near future - no. We have a little problem with ROM size, we should not exceed 102400 bytes limit, and don't know how many space will be occupied by Avatar routines. Maybe later firmwares will be separated for large and small screens, or something else... Don't know. So, it will not be implemented in future release or two.

@docdeath By the way, is 170118 crashing you PC on connect?

**Comment by docdeath** [comment]
nope none off  them have caused problem  here

**Comment by maelstrom2001** [comment]
Charge current is restored to stock in 2 variants:
[170118a](https://dl.dropboxusercontent.com/u/43399149/VTC/arcticfox/nightly/af_170118a.bin) - 1 amp limit
[170118b](https://dl.dropboxusercontent.com/u/43399149/VTC/arcticfox/nightly/af_170118b.bin) - 1,5 amps limit

1,5 amps may be not reached depending on USB source and batteries voltage.
Please test with USB tester, if possible. Thank you!

**Comment by Obicom** [comment]
Currently no more crashes with af170118
Test af170118b: 87% charging level and charging current = 1440 mA

**Comment by Ustes** [comment]
@maelstrom2001 Great job!!

**Comment by docdeath** [comment]
both tested  990.mA  and 1490 mA with external usb charger

**Comment by docdeath** [comment]
@maelstrom2001 did your remove 119 bin if so is there problem with

**Comment by maelstrom2001** [comment]
Faced some problems on boxes with small screen (96x16). On boxes with large screens seems all right.
There is no differences in device support between 170118 and 170119, but 170118 runs on all boxes OK.
I have VTC Mini with 170119 working fine, but Pico with this build have problems.
Nothing critical, just need a bit of time to understand what goes wrong after code cleanup :)

**Comment by docdeath** [comment]
@maelstrom2001 thanks for info as installed it last night and was  trying to  find out what  was wrong with it today as it worked fine / now i know

**Comment by docdeath** [comment]
@maelstrom2001 been 4 days now off use and updated to nightly build 124 and still working a, ok  .just one  thing the latest  build which charging profile is it  1amp or 1.5 amp or normal

**Comment by maelstrom2001** [comment]
@docdeath thank you very much for testing and reports!
Charging is identical to Wismec firmware, i. e. if RX300 can drain 1,5 amps from USB, it will charge about 75% (I think so... not sure, but about it) of total time at 1,5 amps. If charger drop voltage under RX's load, the box will switch to 1 amp, and in the worst cases and near full charge it takes about 0,3..0,5 amps. That cases are overdischarged cells or poor USB adapter.

**Comment by docdeath** [comment]
thanks for info there to must say job well done  there i have used  different coils with loads off different Ohm Atomizer,s and not had any problems to  battery life dose seam to last longer ,thanks docdeath

**Comment by Obicom** [comment]
I can report that the current firmware working well but I have still sporadic reboots if I connect the RX300 to my Windows 10 / 64 bit system. Maybe it is a problem with my specific hardware (new Acer V7 notebook).

**Comment by maelstrom2001** [comment]
@Obicom Most likely, it's the same problem with an USB overload. Or something strange happens on USB 3.0.
If 170118a will not crash your Acer, maybe will be useful to add option to Expert -> USB menu, which will disable 1,5 amps drain and switch box to "old style" charging current value (1,0 A)

**Comment by Obicom** [comment]
It did the same crash with first version with 1A und my batteries are 95% charged (therefore low charging current) ... and is not the USB 3.0 port ....

**Comment by docdeath** [comment]
wops sorry hit wrong button

**Comment by maelstrom2001** [comment]
@Obicom and if it happened with disabled USB charging, I'm completely confused. It should be something very special and unusual :)

**Comment by Obicom** [comment]
Unfortunately yes ... got reboot also with USB charging setting off.

**Comment by docdeath** [comment]
@Obicom i have installed all the test firmware for rx 300 and not one pc crash not even slow down or flicker  i have all so charged my rx on USB 2 and 3 ports no crash which would point to some thing a miss in your pc , to prove point i  did try all firmware in my other pc and still no crash   and charges fine on its USB ports both pc,s running windows 10 64 bit with  one on 32gb men other 8gb

**Comment by docdeath** [comment]
@maelstrom2001 your new firmware 126 works very well and like the charge screen now  good  improvement  on old one

**Comment by maelstrom2001** [comment]
@docdeath Great! :) again, many thanks for testing and fast responses, much appreciated!

**Comment by docdeath** [comment]
@maelstrom2001  after testing for over 2 weeks now i picked up small problem its battery no 1 in tool box monitor  is always showing .5 volts down to test this i have got brand new set off hg4 and new set off 30q  and both charged and both tested on dig volt meter and it shows all battery at  4.23 and in monitor showing batt 1 at 4 .17 and others at 4.23 so  i have to adjust in bvo just heads up there other wise firmware is fault  less thanks

**Comment by MXPYNE** [comment]
Hey buddy,

Just downloaded the latest build....Works like a charm. The only issue is whenever I try to configure using Arctic Fox configuration, it flips my Screen after uploading the settings to my Mod. Help.

**Comment by MXPYNE** [comment]
One more thing, If you could add support from 12/24 Hour int he firmware that'd be great. :)

**Comment by maelstrom2001** [comment]
@MXPYNE 
![](http://i.imgur.com/BOuSPjy.png)

**Comment by Ustes** [comment]
@maelstrom2001 running the latest build with no issues.  Question I have is should I always have to adjust my batteries with BVO?  If I take them fresh off the charger they are 4.2 but there are off in info so I have to adjust in BVO.

**Comment by MXPYNE** [comment]
@maelstrom2001 Thnx a bunch, but I tried that as well and it didn't work. I did download the Beta version of Arctic Fox (Latest) - https://ci.appveyor.com/project/TBXin/NFirmwareEditor/branch/master/artifacts

This seemed to fix the problem. 

Another question is can I charge it with the USB cable provided in the Box ? Cause I don't have an external battery charger at the moment.

Cheers.

**Comment by maelstrom2001** [comment]
@Ustes Don't know how accurate measuring is on RX300. For example, RX200S has very strange behavior: BVO's are quite different for fully charged battery set and for almost empty. So if user want to get more capacity, we recommend to do battery calibration when cells are discharged to ~3,5..3,6 volts. On other side, if he plans to charge battery in box with USB, he should set BVO on fully charged batteries, to eliminate overcharging, imbalance etc.
I think the compromise is to discharge batteries to about 3,7 volts, check voltages with voltmeter that you trust, and then return batteries to box and set BVO to equalize voltages with values you got with voltmeter. This BVO calibration need to do just once.

**Comment by maelstrom2001** [comment]
@MXPYNE all nightly firmwares are compatible with nightly NToolbox builds only, so keep them updated together :)
To be honestly, I don't know which cable is provided by manufacturer. Just note that charge current can be about 1,5 amps. The best solution is to use external charger anyway.

**Comment by MXPYNE** [comment]
@maelstrom2001 Will do brother. 

Just add the 12/24 Hour support in the firmwares.

Cheers

**Comment by Ustes** [comment]
@maelstrom2001 thanks, that is what I did.  I remembered from early you said to use the BVO.

**Comment by docdeath** [comment]
@maelstrom2001  well not sure if this a bug or not but if i use tool box and then set power curve or edit it and then upload to mod it will reset time  then unplug usb  re plug in and time  with then readjust to right time or i can hit upload few times and it will reset to right time

**Comment by maelstrom2001** [comment]
@docdeath thanks! Yep, maybe it's bug, will take a look.

**Comment by maelstrom2001** [comment]
@docdeath please test https://github.com/maelstrom2001/ArcticFox/wiki/Changelog#170201
Seems to be fixed :)

**Comment by docdeath** [comment]
@maelstrom2001  tested and did same again reset time and date  seams to be if you change any off power curve setting in tool box ie change name or time for pre heat

**Comment by maelstrom2001** [comment]
@docdeath updated build, re-download, please, and test again. Thanks in advance!

**Comment by madotha** [comment]
@maelstrom2001 where do I find the NFE Toolbox to edit the settings for af_170201.bin?

**Comment by maelstrom2001** [comment]
@madotha use [nightly NToolbox](https://ci.appveyor.com/project/TBXin/NFirmwareEditor/branch/master/artifacts) for nightly firmwares.

**Comment by docdeath** [comment]
@maelstrom2001  all working fine now tried few times and its not changed good job again  thanks
