### ISSUE TITLE
Logo Upload

### ISSUE THREAD

**Issue by Obicom** [maelstrom2001/ArcticFox#49]
Dear Creator,

I am preparing a review on my YouTube Channel about the ArticFox Firmeware and NFE Toolbox.
(Channel: Obis Dampfer Sofa) Only one point what I am missing is a Logo Upload Option.
Would it be possible to implement this function for further versions?

Best regards, Obi

**Comment by TBXin** [comment]
You can use NFirmwareEditor -> Tools -> Firmware Updater -> Upload logo function

**Comment by maelstrom2001** [comment]
#27

**Comment by Obicom** [comment]
Ok, but I would say it would be more comfortable and not so confusing for beginners if it would possible via the NFE Toolbox ... only my 2 cents
