### ISSUE TITLE
charging issue with cuboid

### ISSUE THREAD

**Issue by gigxy** [maelstrom2001/ArcticFox#5]
Hello,
When i charge a cuboid with usb cable, it charges great, but when the charge is full complet, the batterys are discharging themself until i unplug the usb cable. my battery are new VTC5.
The real time clock and LSL option are disabled.
With an other firmware, i have not this issue.
last night, i lost 20% 
Thanks in advance.

**Comment by TBXin** [comment]
Hi,

Try to disable NoSlp in the Menu -> Settings -> Exper -> USB -> NoSlp.
This setting does not allow device go to sleep while it is connected to the USB.

**Comment by gigxy** [comment]
thanks for reply
this option is allready set to off
