### ISSUE TITLE
[Suggestion] Add custom TFR materials or allow renaming of existing materials

### ISSUE THREAD

**Issue by Sanaki** [maelstrom2001/ArcticFox#51]
When doing complex builds with multiple wire types involved or using exotic types not listed, there can be no proper association available, leaving the requirement to repurpose something with an unrelated name. While this isn't necessary by any means, it would be nice to be able to have a couple custom materials (even if you can't rename those materials beyond CSTM1/CSTM2, etc). Being able to rename existing materials would accomplish the same goal for all intents and purposes.

**Comment by TBXin** [comment]
Hmmm...

You can rename all 8 TFR materials, also you can export curves and import them, even more - you can download curve from steam-engine and import to your box.

![](http://i.imgur.com/uRUneZ3.png)

![](http://i.imgur.com/nslN3z0.png)

**Comment by Sanaki** [comment]
Well crap, I didn't see the profile rename option in there. I've been using steam engine imports for my coils as it is. Not sure how I missed that. Thanks. Closing this one, I'm more than happy with that.

**Comment by Luminescah** [comment]
Sorry for reviving, but I'm having a problem when I try importing custom .csv from steam-engine.
http://imgur.com/CBVUrHQ

**Comment by maelstrom2001** [comment]
@Luminescah steam-engine has changed export format, please update NToolbox to [the recent nightly](https://ci.appveyor.com/project/TBXin/NFirmwareEditor/branch/master/artifacts)

**Comment by Luminescah** [comment]
Works fine. 
Thanks!
One quick question, I don't think this warrants an extra thread. 
On the homescreen, how can I quickly change the temperature? Plus/minus seems to only change the wattage.

**Comment by maelstrom2001** [comment]
Set Temperature Dominant option in NToolbox for current profile:

![](http://i.imgur.com/9hAn41U.png)

or assign Multiclick to toggle this option:

![](http://i.imgur.com/hwieC9B.png)

To change non-dominant regulation press Fire 4 times - you'll enter in edit main screen mode, it's the same as 3 clicks in stock Joyetech firmwares.

**Comment by Luminescah** [comment]
Thanks again.
Great firmware, much appreciated for your work.
