### ISSUE TITLE
TC100W Installing issue

### ISSUE THREAD

**Issue by Prole97** [maelstrom2001/ArcticFox#52]
i can't install the version of af170103 on my istick tc 100w because the nfe toolbox (last version) show me "Opened firmware file is not suitable for the connected device."

**Comment by TBXin** [comment]
Redownload firmware file and try again.

**Comment by Prole97** [comment]
i download the same firmware 2 attemp, nothing, the version af16xxxx go

**Comment by Prole97** [comment]
for the update i use nfe toolbox 1.4

**Comment by Obicom** [comment]
I tried it on three different iStick TC100W devices now with Toolbox v1.4 and ArticFox 170103 build and found no problems. Therefore I can't confirm an general issue.

**Comment by Prole97** [comment]
Thank you, i solved

**Comment by Prole97** [comment]
A very good work! Good lucky for the future!
