### ISSUE TITLE
BVO with RX300

### ISSUE THREAD

**Issue by Obicom** [maelstrom2001/ArcticFox#53]
It looks like that BVO for batterie 4 with RX300 do not work.
I can adjust all 4 values but on bat 4 there is no effect under info display
(nightly build 170114b)

**Comment by maelstrom2001** [comment]
Strange... Is battery voltage B4 changing on BVO screen while you changing its offset?

**Comment by Obicom** [comment]
I hope understand your question right. If I change the values for all four batteries on BVO with Toolbox yes the offset value is changing on screen.  Afterwards I checked my battery values on the "Info screen on the device" and B1-B3 are changing but not B4.

**Comment by TBXin** [comment]
@Obicom thanks for feedback. Thats NFE Toolbox issue.

**Comment by TBXin** [comment]
@Obicom try, please, [this build[(https://ci.appveyor.com/project/TBXin/nfirmwareeditor/build/6.4.20/artifacts).

**Comment by Obicom** [comment]
@TBXin : With the new nightly build of TB (6.4.20) the issue is solved. Issue can be closed. Thank you :)

**Comment by TBXin** [comment]
Nice!
