### ISSUE TITLE
View of clock on mainscreen

### ISSUE THREAD

**Issue by hawkeyexp** [maelstrom2001/ArcticFox#54]
Hi, i have clock enabled on screen which works fine. On hold fire clock is replaved by values (pwr/coil/amp) - but after unpush fire values are instantly replaced again by clock. It would be nice to have 2-3 secs. to have a look on the values before clock is shown again.

**Comment by maelstrom2001** [comment]
OK, we'll change clock behavior in next release, it will be displayed like logo, i. e. after 3 seconds of inactivity.

**Comment by hawkeyexp** [comment]
works great on nightly ! Thx
