### ISSUE TITLE
Boot screen

### ISSUE THREAD

**Issue by Nihilus89** [maelstrom2001/ArcticFox#55]
The screen with the ArcticFox logo when the device opens (after 5 clicks). Is it possible to turn this off? I find the delay from switching the device on to actually being able to vape annoying.

**Comment by Obicom** [comment]
and if not ... would it be possible to replace the logo with an own one? ;)

**Comment by maelstrom2001** [comment]
@Nihilus89 Press Fire button one more time and splash will be hided, no need to wait 2..3 sec. Box by itself is ready to fire after power on in approx. 0,3..0,5 s, with splash screen or without it.
@Obicom Use NFirmwareEditor to edit any graphics.
