### ISSUE TITLE
RX300 / af170116 / no charching

### ISSUE THREAD

**Issue by Obicom** [maelstrom2001/ArcticFox#57]
With new nightly build (and older) no charging on my RX300. Would expect that new nightly build should charge the box regarding the change log topic:  balancer routines for RX300 and Pico Dual
Is a bug or a feature? ;)

**Comment by maelstrom2001** [comment]
Balancer should work. Charging - not. It's done, but disabled, until someone desperate wants to test it :-D

**Comment by TBXin** [comment]
You can find all infos about changes in the changelog, which is located near nighlty builds.

170114
------
[!] RX300 support bugfixes, now works all except USB charging and Avatar support
