### ISSUE TITLE
RXmini - Display flipped

### ISSUE THREAD

**Issue by Obicom** [maelstrom2001/ArcticFox#58]
After installation of af170203.bin on my RXmini the display was flipped and I must set checkbox "flipped" to get the display in right orientation. Not a big deal but maybe worth to mention. ;)

**Comment by maelstrom2001** [comment]
Thank you! Will include "cuboid style" default display orientation in release :)

**Comment by Obicom** [comment]
Feedback: Issue with wrong display rotation is solved with af17017.bin
Topic could be closed
