### ISSUE TITLE
[Question] Can firmware control battery charging?

### ISSUE THREAD

**Issue by Nefelim4ag** [maelstrom2001/ArcticFox#6]
Hi, i have a RX2/3 device, so question is about battery balancing algorithm, can i control it someway?

Thanks.

**Comment by TBXin** [comment]
Hi,

No, we can't control it. 
Charging is pure hardware feature, firmware can only turn on or off it.

In addition, for devices with a single battery we can not even turn off charging... pure hardware implementation.

**Comment by Nefelim4ag** [comment]
So sad, thank you.
