### ISSUE TITLE
Egrip 2 LED light support

### ISSUE THREAD

**Issue by AAI688** [maelstrom2001/ArcticFox#62]
Sorry if i bombard u with questions and features. I got an egrip 2 coming and i was wondering if the led light support would be available as i dont see it in the menu structure. Would it be easy to add? Cheers for it.. ^_^

**Comment by dante-35** [comment]
Evic Aio has same feature too.
Its very handy to see liqud status in dark places.

**Comment by StillVoidingWarranties** [comment]
I own a Joyetech eGrip II Light and would love to see support for the tank light. I volunteer to test any beta releases of ArcticFox.

**Comment by maelstrom2001** [comment]
Will be added to upcoming release as well as for eVic AIO and Pico RDTA.

**Comment by maelstrom2001** [comment]
Released.

**Comment by AAI688** [comment]
hi just tested the new nightly 09. where is the LED light settings? i cant seem to find it??

**Comment by maelstrom2001** [comment]
Hello! There is no settings for this option, LED should light while you press Fire button.

**Comment by komaramnt** [comment]
I opened new tread, but I will ask in here... can we get a option ot turn it off or change colors please........ I know it is hard to do things for everyone but if we can help with something just name it

sorry for my bad English
