### ISSUE TITLE
Limitations?

### ISSUE THREAD

**Issue by JayBee23** [maelstrom2001/ArcticFox#65]
Hi,
how are the Resistance-, Voltage- and Amp-Limitations with this Firmware?
Are they changing?
Are you able to change them?
I'm specially interested in the Resistance, would be awesome to fire below 0.1 Ohms...

Thanks,
JayBee

**Comment by TBXin** [comment]
Hello,

Resistance; 0.1 Ohm in the VW mode and 0.05 Ohm in the TC mode;
Voltage: depending on the box model: 9-9.99V;
Current: depending on the box model: 25-50A;

> Are you able to change them?
No.

> I'm specially interested in the Resistance, would be awesome to fire below 0.1 Ohms...
It is not safety, so we will not do this.
