### ISSUE TITLE
Clock Issue

### ISSUE THREAD

**Issue by ebi-peer** [maelstrom2001/ArcticFox#69]
Firstly i must say this firmware is amazing, Developers did a fantastic job in my opinion every vape should use ArcticFox. I currently have it on a Wismec Reuleaux RX2/3. 

_Issues I found_

1. If i remove my batteries to charge them when i insert them back in the clock and date reset
2. Iv also noticed the clock is jumping ahead of time for example if the time now it 4:40 PM (same on device and current time) tomorrow at 3:40 PM(current time) the device will show the time as 4 PM 

Another thing that i noticed was my coil readings, its reading at 0.28Ω  but when i fire it reads 0.30Ω.
is there a way for it to lock the resistance it reads from the coil like the original firmware?

**Comment by maelstrom2001** [comment]
Wismec Reuleaux RX2/3 has no hardware RTC module. When you changing batteries, software RTC module resets. Switching X32 option off and LSL option to on will give you accurate clock. Again, until battery replacement. If you want clock that will not resets during battery replacement, buy VTwo Mini or something else with hardware RTC module and little backup battery.

Realtime coil measurement (while you press Fire) in VW profile is more useful than original style of displaying of resistance. You'll be able to find any problems with your atomizer such as loosed screws etc.
Note that original firmare also measured coil in realtime in VariWatt mode, but displayed resistance detected while atomizer screwing, which can be wrong.
