### ISSUE TITLE
[Suggestion] Lock Fire Button

### ISSUE THREAD

**Issue by heru21** [maelstrom2001/ArcticFox#71]
hey admin,

i hope for next update frimware include features **lock fire button** 

for example if device in standby mode for 20sec device made auto lock fire button
i think it be more safety features if we forget to turn off device and we put device to pocket or vapor bag 

thanks

**Comment by TBXin** [comment]
And how this feature should work?

Okay, after 20 sec delay fire button will be locked - how user should unlock it?
E.g. user should press fire button a few times? there is already working solution - 5 clicks to turn on/off device.

**Comment by heru21** [comment]
**active in click menu 2x click is an empty slot it can be add in 2x click to lock fire button on/off and still be customize** 

i think add this feature in click menu add some lock fire button its a great deal its like a DNA if have a lock fire button...

**_this firmware its can be kill DNA and YIHI_**

_i use for a week, i think use this frimware its a great choice favor production ok, its great read temperatur and most i like Preheat setting its so so great_

i use **Evic Mini Vtc** and **Wismec RX200s**
![upload](https://cloud.githubusercontent.com/assets/25250586/22174017/f877aee0-e005-11e6-91b0-54f2d9d6917f.jpg)

**Comment by heru21** [comment]
2 click to on/off lock fire button and still be change if user dont want it
from control to change that and 5 click to on/off device
Pada tanggal 21 Jan 2017 00.24, "ReikoKitsune" <notifications@github.com>
menulis:

**Comment by madotha** [comment]
I'd also welcome this, that you can edit a 2,3,4 click to lock the fire button and adjustment buttons.
Just like on a YiHi chip, where you can 3-click-lock device (although there's the shutdown function hidden in the 5-click-menu)

**Comment by heru21** [comment]
Yes but it more like dna chip... When we have a lock fire button for more
safety...

I'd also welcome this, that you can edit a 2,3,4 click to lock the fire
button and adjustment buttons.
Just like on a YiHi chip, where you can 3-click-lock device (although
there's the shutdown function hidden in the 5-click-menu)

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/maelstrom2001/ArcticFox/issues/71#issuecomment-276682884>,
or mute the thread

**Comment by tiryaki92** [comment]
It is not in the click menu. As with some Smok devices, the + and - keys and the fire button must be locked when the + and - keys are pressed for a quarter of a second. This is much more useful

**Comment by maelstrom2001** [comment]
Released.
