### ISSUE TITLE
Main screen Edit navigation.

### ISSUE THREAD

**Issue by ArionWT** [maelstrom2001/ArcticFox#74]
Don't working back "-" button in Main screen Edit mode.

**Comment by TBXin** [comment]
"-" should select next available element.

**Comment by ArionWT** [comment]
> "-" should select next available element.
Don't work on 96x16 display.

**Comment by TBXin** [comment]
Works perfectly ^^

In VW you can only bottom line;
In TC you can change on bottom line and lock/unlock resistance (default upper line);

**Comment by ArionWT** [comment]
Thanks 😊
