### ISSUE TITLE
required lower temperature eleaf pico

### ISSUE THREAD

**Issue by golijeevankumar** [maelstrom2001/ArcticFox#80]
can i get lower temperature than 100 c that will help me 
starts from 20 c 
mod eleaf pico 75w

**Comment by TBXin** [comment]
Ehm... in your room temperature is higher than 20c.

**Comment by maelstrom2001** [comment]
> starts from 20 c

For what purposes?

**Comment by golijeevankumar** [comment]
I can't vape from 100 c it's too high for me and I want to vape in low
temperature

**Comment by TBXin** [comment]
Did you know, that water has 100c boiling point? >__<
Vape liquid have a higher boiling point, so, how will you vape without steam?

**Comment by golijeevankumar** [comment]
I can't take 100 c temperature so asking if I can lower than 100

**Comment by TBXin** [comment]
Okay, you can.

Step 1: Open your liquid bottle;
Step 2: Start breathing;
Step 3: ???
Step 4: Profit!

**Comment by golijeevankumar** [comment]
Thanks for your suggestions
If u can't help me out don't give me all nonsense methods

**Comment by sandbagjohnny** [comment]
He's trying to tell you that your request doesn't make sense because ejuice barely vaporizes at 100c to begin with. I've never seen any production device (including the DNA boxes) myself; There's a reason for that :)

**Comment by Hunterror77** [comment]
resistance is not lock correctly.... this is the problem. You do not need to go any lower than 100 c.
