### ISSUE TITLE
Is the code opensource?

### ISSUE THREAD

**Issue by andreivoinea93** [maelstrom2001/ArcticFox#83]
Hello,

First of all I want to thank you for your effort, you're really putting new life in our devices. Your project is a really wonderful alternative to DNA devices and Evolv's software.

I have some knowledge regarding microcontrollers, Atmels and Microchips mostly and I'm willing to help your project in my spare time, if I will be able to make someone quit smoking and save a life with a pull request, why not? I can't find the source code for the firmware anywhere on this github project. Is it opensource? If so, where can I find it?

Have a great day!

**Comment by maelstrom2001** [comment]
Thanks! Currently firmware is distributed "as is", no source code provided.

**Comment by andreivoinea93** [comment]
Are there any plans on doing so?

**Comment by maelstrom2001** [comment]
At this point no. Maybe later, when we'll stop development and support.
