### ISSUE TITLE
EleafPico HW:1.0 X32 setting.

### ISSUE THREAD

**Issue by dante-35** [maelstrom2001/ArcticFox#84]
hi
When you set X32 setting to on in EleafPico HW:1.0 , it automaticly sets if off when you replace battery.

**Comment by TBXin** [comment]
X32 is not available on the Pico.

**Comment by maelstrom2001** [comment]
From readme:
X32 - RTC module uses secondary 32768 Hz oscillator, _if present_

Pico has no secondary oscillator by design.
