### ISSUE TITLE
[Suggestion] Put board temperature back on extended charge screen for large screen mods.

### ISSUE THREAD

**Issue by traviswparker** [maelstrom2001/ArcticFox#85]
Older versions of AF had the board temperature and the lowest battery voltage on the extended charge screen.

This is still the layout for the small screen, but the large screen only displays battery voltages. 

Is it possible we could have board temperature and all batteries?

**Comment by maelstrom2001** [comment]
Thanks for suggestion, thinking about redesign too. We'll come up with something :)

**Comment by maelstrom2001** [comment]
Done in nightly 170126. Battery percentage and board temperature rotating with 5 sec interval, for multi-cells boxes only.
