### ISSUE TITLE
Any chance for other devices? 

### ISSUE THREAD

**Issue by pannal** [maelstrom2001/ArcticFox#90]
I'd love to see this firmware on the asmodus minikin 2 for example. Would that be possible? Or is the firmware based on a common chip the supported devices use? 

Thanks

**Comment by maelstrom2001** [comment]
> is the firmware based on a common chip the supported devices use?

Yes, it is. Asmodus, Smok etc. are completely different, so we can't tell about porting firmware, it should be another project.

**Comment by pannal** [comment]
Ok, thank you :)
