### ISSUE TITLE
Please add power bank mode like rs300x!

### ISSUE THREAD

**Issue by userdsp** [maelstrom2001/ArcticFox#93]
Please add power bank mode like rs300x! Im asking specially about rx200s

**Comment by Wietjuh** [comment]
would love to see this... especially for on festivals/on the road

**Comment by docdeath** [comment]
really i own rx300 my self and no way would i trust it as power bank  to. its just gimmick  added as selling point.  i got mine for battery life for vaping and nothing more

**Comment by wulfgrim** [comment]
This right here... I'm not sure it'd be worth the effort it would take to make it happen, It would be cool as hell. but you're looking at taking a device that's designed and programmed to drive a restive load and telling it to drive a LC load. there could be issues.

the rx300 might have extra hardware to make this possible.

while the device can drive a TC load, that would be similar to having it hold  a steady 5.1V on it's output. I dunno....

**Comment by maelstrom2001** [comment]
Released.
