### ISSUE TITLE
[Bug or Feature?] X32 ON disables USB charging on Cuboid 200 (FW20170126)

### ISSUE THREAD

**Issue by FrankBKK** [maelstrom2001/ArcticFox#95]
I thought the X32 is related to the RTC functions only but when turning this option on the USB charging won't work anymore on the Cuboid 200 on the latest nightly build 20170126.

**Comment by maelstrom2001** [comment]
It's very strange, need time to investigate. On other side, you should keep X32 off because Cuboid has no secondary oscillator for RTC module. If you want accurate clock, better turn LSL on.
