### ISSUE TITLE
[Question] Battery discharge profiles - Info needed

### ISSUE THREAD

**Issue by FrankBKK** [maelstrom2001/ArcticFox#96]
Can someone point me to more information on how to create discharge profiles for individual battery types ? 
Where and/or how to find the proper data sheets etc.

**Comment by smok-e** [comment]
which batteries? data sheets might be somewhere on the i-net, have you tried google?

**Comment by smok-e** [comment]
and you can search for mooch the battery guru ;-)

**Comment by maelstrom2001** [comment]
@FrankBKK you can use discharge profiles for DNA, for example. But the most precise result you can get if you did it yourself. Charge battery full, reset statistics, vape and fill table like that:
![](http://i.imgur.com/KTViFnj.png)
It contains pairs of numbers, total vaping time and battery voltage. Then make chart and draw the same in NToolbox.

**Comment by FrankBKK** [comment]
Perfect - Thanks for the Info !
