### ISSUE TITLE
RX mini

### ISSUE THREAD

**Issue by Drosses** [maelstrom2001/ArcticFox#97]
When i click on ArticFox configuration, it shows an error "Unable to download device settings. Restart your device".

Someone else with the same mod? What I am doing wrong?

**Comment by maelstrom2001** [comment]
Did you flash ArcticFox and which build? What version of NToolbox you are using?

**Comment by Drosses** [comment]
I am using the last version of NToolbox, but I dont see any .bin to update my firmware, where can I download it?

Thanks!

**Comment by Drosses** [comment]
Ohhhh i found it! sorry i am very retard :D
