### ISSUE TITLE
eViv VTC Dual

### ISSUE THREAD

**Issue by Neoschamane** [maelstrom2001/ArcticFox#98]
In the BVO settings, the batteries are reversed. The battery 1 can be adjusted via the battery 2 and the battery 2 can be adjusted via the battery 3.

**Comment by Wietjuh** [comment]
Same here.

**Comment by Neoschamane** [comment]
NFE Toolbox v1.4 and ArcticFox 170103

**Comment by maelstrom2001** [comment]
Yep, known issue. BVO1 was used for 1 cell configuration, and BVO2/3 - for 2 cells. Fixed since 170117, use BVO1/2 in both configurations.

**Comment by Wietjuh** [comment]
Nightly is ok! just confirmed..

BTW last nightly is a treat! have to get along with translating in to dutch...
